# Module 7: GUI over all network attacks

In [1]:
#import library packages
import pandas as p
import matplotlib.pyplot as plt
import seaborn as s
import numpy as n

In [2]:
# feature names
features = ["duration", "protocol_type", "service", "flag", "src_bytes", "dst_bytes", "land", "Wrong_fragment", "Urgent", "hot", "num_failed_login", "logged_in", "num_compromised", "root_shell", "su_attempted", "num_root", "num_file_creations", "num_shells", "num_access_files", "num_outbound_cmds", "is_host_login", "is_guest_login", "count", "srv_count", "serror_rate", "srv_serror_rate", "rerror_rate", "srv_rerror_rate", "same_srv_rate", "diff_srv_rate", "srv_diff_host_rate", "dst_host_count", "dst_host_srv_count", "dst_host_same_srv_rate", "dst_host_diff_ srv_rate", "dst_host_same_src_port_rate", "dst_host_srv_diff_host _rate", "dst_host_serror_rate", "dst_host_srv_serror_rate", "dst_host_rerror_rate", "dst_host_srv_rerror_rate","class"] 
data = p.read_csv("data.csv", names = features)

In [3]:
df=data.dropna()

In [4]:
df['class'].unique()

array(['normal.', 'snmpgetattack.', 'named.', 'xlock.', 'smurf.',
       'ipsweep.', 'multihop.', 'xsnoop.', 'sendmail.', 'guess_passwd.',
       'saint.', 'buffer_overflow.', 'portsweep.', 'pod.', 'apache2.',
       'phf.', 'udpstorm.', 'warezmaster.', 'perl.', 'satan.', 'xterm.',
       'mscan.', 'processtable.', 'ps.', 'nmap.', 'rootkit.', 'neptune.',
       'loadmodule.', 'imap.', 'back.', 'httptunnel.', 'worm.',
       'mailbomb.', 'ftp_write.', 'teardrop.', 'land.', 'sqlattack.',
       'snmpguess.'], dtype=object)

In [5]:
df['attack'] = df['class'].map({'normal.':0, 'snmpgetattack.':1, 'named.':1, 'xlock.':1, 'smurf.':1,
       'ipsweep.':1, 'multihop.':1, 'xsnoop.':1, 'sendmail.':1, 'guess_passwd.':1,
       'saint.':1, 'buffer_overflow.':1, 'portsweep.':1, 'pod.':1, 'apache2.':1,
       'phf.':1, 'udpstorm.':1, 'warezmaster.':1, 'perl.':1, 'satan.':1, 'xterm.':1,
       'mscan.':1, 'processtable.':1, 'ps.':1, 'nmap.':1, 'rootkit.':1, 'neptune.':1,
       'loadmodule.':1, 'imap.':1, 'back.':1, 'httptunnel.':1, 'worm.':1,
       'mailbomb.':1, 'ftp_write.':1, 'teardrop.':1, 'land.':1, 'sqlattack.':1,
       'snmpguess.':1})

In [6]:
df['Attack_Type'] = df['class'].map({'normal.':'No_Attack_Occurs', 'snmpgetattack.':'SNMPget_Attack',
                                     'named.':'Named_Attack', 'xlock.':'Xlock_Attack', 'smurf.':'Smurf_Attack',
       'ipsweep.':'IPsweep_Attack', 'multihop.':'Multihop_Attack', 'xsnoop.':'Xsnoop_Attack', 'sendmail.':'Sendmail_Attack',
                                     'guess_passwd.':'Guess_passwd_Attack',
       'saint.':'Saint_Attack', 'buffer_overflow.':'Buffer_overflow_Attack', 'portsweep.':'Portsweep_Attack',
                                     'pod.':'Pod_Attack', 'apache2.':'Apache2_Attack',
       'phf.':'PHF_Attack', 'udpstorm.':'UDPstorm_Attack', 'warezmaster.':'Warezmaster_Attack', 'perl.':'Perl_Attack',
                                     'satan.':'Satan_Attack', 'xterm.':'Xterm_Attack',
       'mscan.':'Mscan_Attack', 'processtable.':'Processtable_Attack', 'ps.':'PS_Attack', 'nmap.':'NMAP_Attack',
                                     'rootkit.':'Rootkit_Attack', 'neptune.':'Neptune_Attack',
       'loadmodule.':'Loadmodule_Attack', 'imap.':'IMAP_Attack', 'back.':'Back_Attack',
                                     'httptunnel.':'HTTPtunnel_Attack', 'worm.':'Worm_Attack',
       'mailbomb.':'Mailbomb_Attack', 'ftp_write.':'FTP_Write_Attack', 'teardrop.':'Teardrop_Attack',
                                     'land.':'Land_Attack', 'sqlattack.':'SQL_Attack',
       'snmpguess.':'SNMPguess_Attack'})

In [7]:
df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,Wrong_fragment,Urgent,hot,...,dst_host_diff_ srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host _rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class,attack,Attack_Type
0,0,udp,private,SF,105,146,0,0,0,0,...,0.01,0.00,0.0,0.0,0.0,0.0,0.0,normal.,0,No_Attack_Occurs
1,0,udp,private,SF,105,146,0,0,0,0,...,0.01,0.00,0.0,0.0,0.0,0.0,0.0,normal.,0,No_Attack_Occurs
2,0,udp,private,SF,105,146,0,0,0,0,...,0.01,0.00,0.0,0.0,0.0,0.0,0.0,normal.,0,No_Attack_Occurs
3,0,udp,private,SF,105,146,0,0,0,0,...,0.01,0.00,0.0,0.0,0.0,0.0,0.0,snmpgetattack.,1,SNMPget_Attack
4,0,udp,private,SF,105,146,0,0,0,0,...,0.01,0.01,0.0,0.0,0.0,0.0,0.0,snmpgetattack.,1,SNMPget_Attack

In [8]:
from tkinter import *

In [9]:
del df["duration"]
del df["land"]
del df["Urgent"]
del df["hot"]
del df["num_failed_login"]
del df["logged_in"]
del df["num_compromised"]
del df["root_shell"]
del df["is_host_login"]
del df["is_guest_login"]

In [10]:
del df['num_root']
del df['num_file_creations']
del df['num_shells']
del df['num_outbound_cmds']
del df['count']
del df['srv_count']
del df['srv_serror_rate']
del df['srv_rerror_rate']
del df['same_srv_rate']
del df['diff_srv_rate']
del df['srv_diff_host_rate']
del df['dst_host_count']
del df['dst_host_srv_count']
del df['dst_host_same_srv_rate']
del df['dst_host_diff_ srv_rate']
del df['dst_host_same_src_port_rate']
del df['dst_host_srv_diff_host _rate']
del df['dst_host_serror_rate']
del df['dst_host_srv_serror_rate']
del df['dst_host_rerror_rate']
del df['dst_host_srv_rerror_rate']

del df['su_attempted']
del df['num_access_files']

In [11]:
df.columns

Index(['protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes',
       'Wrong_fragment', 'serror_rate', 'rerror_rate', 'class', 'attack',
       'Attack_Type'],
      dtype='object')

In [12]:
df['protocol_type'].unique()

array(['udp', 'tcp', 'icmp'], dtype=object)

In [13]:
df['UDP'] = df.protocol_type.map({'udp':1, 'tcp':0, 'icmp':0})
df['TCP'] = df.protocol_type.map({'udp':0, 'tcp':1, 'icmp':0})
df['ICMP'] = df.protocol_type.map({'udp':0, 'tcp':0, 'icmp':1})

In [14]:
del df['protocol_type']

In [15]:
df['service'].unique()

array(['private', 'domain_u', 'http', 'smtp', 'ftp_data', 'ftp', 'eco_i',
       'other', 'auth', 'ecr_i', 'IRC', 'X11', 'finger', 'time', 'domain',
       'telnet', 'pop_3', 'ldap', 'login', 'name', 'ntp_u', 'http_443',
       'sunrpc', 'printer', 'systat', 'tim_i', 'netstat', 'remote_job',
       'link', 'urp_i', 'sql_net', 'bgp', 'pop_2', 'tftp_u', 'uucp',
       'imap4', 'pm_dump', 'nnsp', 'courier', 'daytime', 'iso_tsap',
       'echo', 'discard', 'ssh', 'whois', 'mtp', 'gopher', 'rje', 'ctf',
       'supdup', 'hostnames', 'csnet_ns', 'uucp_path', 'nntp',
       'netbios_ns', 'netbios_dgm', 'netbios_ssn', 'vmnet', 'Z39_50',
       'exec', 'shell', 'efs', 'klogin', 'kshell', 'icmp'], dtype=object)

In [16]:
df['private'] = df.service.map({'private':1, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['domain_u'] = df.service.map({'private':0, 'domain_u':1, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['http'] = df.service.map({'private':0, 'domain_u':0, 'http':1, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['smtp'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':1, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['ftp_data'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':1, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['ftp'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':1, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['eco_i'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':1,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

In [17]:
df['other'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':1, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['auth'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':1, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['ecr_i'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':1, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['IRC'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':1, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['X11'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':1, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['finger'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':1, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['time'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':1, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

In [18]:
df['domain'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':1,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['telnet'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':1, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['pop_3'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':1, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['ldap'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':1, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['login'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':1, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['name'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':1, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['ntp_u'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':1, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['http_443'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':1,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['sunrpc'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':1, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['printer'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':1, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['systat'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':1, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

df['tim_i'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':1,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

In [19]:
df['service'].unique()

array(['private', 'domain_u', 'http', 'smtp', 'ftp_data', 'ftp', 'eco_i',
       'other', 'auth', 'ecr_i', 'IRC', 'X11', 'finger', 'time', 'domain',
       'telnet', 'pop_3', 'ldap', 'login', 'name', 'ntp_u', 'http_443',
       'sunrpc', 'printer', 'systat', 'tim_i', 'netstat', 'remote_job',
       'link', 'urp_i', 'sql_net', 'bgp', 'pop_2', 'tftp_u', 'uucp',
       'imap4', 'pm_dump', 'nnsp', 'courier', 'daytime', 'iso_tsap',
       'echo', 'discard', 'ssh', 'whois', 'mtp', 'gopher', 'rje', 'ctf',
       'supdup', 'hostnames', 'csnet_ns', 'uucp_path', 'nntp',
       'netbios_ns', 'netbios_dgm', 'netbios_ssn', 'vmnet', 'Z39_50',
       'exec', 'shell', 'efs', 'klogin', 'kshell', 'icmp'], dtype=object)

In [20]:
df['netstat'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':1, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['remote_job'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':1,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['link'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':1, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['urp_i'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':1, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['sql_net'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':1, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['bgp'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':1, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['pop_2'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':1, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['tftp_u'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':1, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['uucp'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':1,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['imap4'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':1, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

In [21]:
df['pm_dump'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':1, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['nnsp'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':1, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['courier'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':1, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['daytime'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':1, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['iso_tsap'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':1,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['echo'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':1, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['discard'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':1, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['ssh'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':1, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['whois'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':1, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['mtp'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':1, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

In [22]:
df['gopher'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':1, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['rje'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':1, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['ctf'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':1,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['supdup'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':1, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['hostnames'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':1, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['csnet_ns'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':1, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['uucp_path'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':1, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['nntp'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':1,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['netbios_ns'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':1, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['netbios_dgm'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':1, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})

In [23]:
df['netbios_ssn'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':1, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['vmnet'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':1, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['Z39_50'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':1,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['exec'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':1, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['shell'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':1, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':0})
df['efs'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':1, 'klogin':0, 'kshell':0, 'icmp':0})
df['klogin'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':1, 'kshell':0, 'icmp':0})
df['kshell'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':1, 'icmp':0})
df['icmp'] = df.service.map({'private':0, 'domain_u':0, 'http':0, 'smtp':0, 'ftp_data':0, 'ftp':0, 'eco_i':0,
       'other':0, 'auth':0, 'ecr_i':0, 'IRC':0, 'X11':0, 'finger':0, 'time':0, 'domain':0,
       'telnet':0, 'pop_3':0, 'ldap':0, 'login':0, 'name':0, 'ntp_u':0, 'http_443':0,
       'sunrpc':0, 'printer':0, 'systat':0, 'tim_i':0,'netstat':0, 'remote_job':0,
       'link':0, 'urp_i':0, 'sql_net':0, 'bgp':0, 'pop_2':0, 'tftp_u':0, 'uucp':0,
       'imap4':0, 'pm_dump':0, 'nnsp':0, 'courier':0, 'daytime':0, 'iso_tsap':0,
       'echo':0, 'discard':0, 'ssh':0, 'whois':0, 'mtp':0, 'gopher':0, 'rje':0, 'ctf':0,
       'supdup':0, 'hostnames':0, 'csnet_ns':0, 'uucp_path':0, 'nntp':0,
       'netbios_ns':0, 'netbios_dgm':0, 'netbios_ssn':0, 'vmnet':0, 'Z39_50':0,
       'exec':0, 'shell':0, 'efs':0, 'klogin':0, 'kshell':0, 'icmp':1})

In [24]:
del df['service']

In [25]:
df['SF'] = df.flag.map({'SF':1, 'RSTR':0, 'S1':0, 'REJ':0, 'S3':0, 'RSTO':0, 'S0':0, 'S2':0})
df['RSTR'] = df.flag.map({'SF':0, 'RSTR':1, 'S1':0, 'REJ':0, 'S3':0, 'RSTO':0, 'S0':0, 'S2':0})
df['S1'] = df.flag.map({'SF':0, 'RSTR':0, 'S1':1, 'REJ':0, 'S3':0, 'RSTO':0, 'S0':0, 'S2':0})
df['REJ'] = df.flag.map({'SF':0, 'RSTR':0, 'S1':0, 'REJ':1, 'S3':0, 'RSTO':0, 'S0':0, 'S2':0})
df['S3'] = df.flag.map({'SF':0, 'RSTR':0, 'S1':0, 'REJ':0, 'S3':1, 'RSTO':0, 'S0':0, 'S2':0})
df['RSTO'] = df.flag.map({'SF':0, 'RSTR':0, 'S1':0, 'REJ':0, 'S3':0, 'RSTO':1, 'S0':0, 'S2':0})
df['S0'] = df.flag.map({'SF':0, 'RSTR':0, 'S1':0, 'REJ':0, 'S3':0, 'RSTO':0, 'S0':1, 'S2':0})
df['S2'] = df.flag.map({'SF':0, 'RSTR':0, 'S1':0, 'REJ':0, 'S3':0, 'RSTO':0, 'S0':0, 'S2':1})

In [26]:
del df['flag']

In [27]:
df.columns

Index(['src_bytes', 'dst_bytes', 'Wrong_fragment', 'serror_rate',
       'rerror_rate', 'class', 'attack', 'Attack_Type', 'UDP', 'TCP', 'ICMP',
       'private', 'domain_u', 'http', 'smtp', 'ftp_data', 'ftp', 'eco_i',
       'other', 'auth', 'ecr_i', 'IRC', 'X11', 'finger', 'time', 'domain',
       'telnet', 'pop_3', 'ldap', 'login', 'name', 'ntp_u', 'http_443',
       'sunrpc', 'printer', 'systat', 'tim_i', 'netstat', 'remote_job', 'link',
       'urp_i', 'sql_net', 'bgp', 'pop_2', 'tftp_u', 'uucp', 'imap4',
       'pm_dump', 'nnsp', 'courier', 'daytime', 'iso_tsap', 'echo', 'discard',
       'ssh', 'whois', 'mtp', 'gopher', 'rje', 'ctf', 'supdup', 'hostnames',
       'csnet_ns', 'uucp_path', 'nntp', 'netbios_ns', 'netbios_dgm',
       'netbios_ssn', 'vmnet', 'Z39_50', 'exec', 'shell', 'efs', 'klogin',
       'kshell', 'icmp', 'SF', 'RSTR', 'S1', 'REJ', 'S3', 'RSTO', 'S0', 'S2'],
      dtype='object')

In [28]:
df['src_bytes'].unique()

array([ 105,   29,  223, ..., 2575, 5820, 2717], dtype=int64)

In [29]:
list(df['src_bytes'])

[105,
 105,
 105,
 105,
 105,
 105,
 29,
 105,
 105,
 223,
 105,
 230,
 105,
 105,
 3170,
 297,
 291,
 295,
 105,
 105,
 268,
 105,
 223,
 227,
 222,
 740,
 105,
 35195,
 8325,
 105,
 105,
 105,
 105,
 559,
 227,
 105,
 317,
 1661,
 232,
 322,
 321,
 234,
 218,
 216,
 615,
 312,
 105,
 307,
 105,
 105,
 246,
 105,
 245,
 105,
 908,
 105,
 232,
 235,
 249,
 105,
 105,
 105,
 235,
 243,
 236,
 237,
 240,
 240,
 315,
 313,
 105,
 1018,
 1145,
 105,
 105,
 244,
 275,
 247,
 245,
 884,
 854,
 105,
 30,
 105,
 105,
 105,
 105,
 105,
 45,
 1625,
 105,
 1214,
 105,
 299,
 291,
 252,
 43,
 105,
 859,
 764,
 15722,
 151,
 105,
 45,
 1145,
 44,
 765,
 105,
 45,
 2229,
 44,
 315,
 294,
 305,
 105,
 105,
 105,
 286,
 278,
 315,
 296,
 323,
 105,
 340,
 9,
 105,
 105,
 1483,
 105,
 105,
 105,
 105,
 910,
 105,
 224,
 163,
 45,
 299,
 296,
 296,
 289,
 46,
 105,
 46,
 105,
 192,
 45,
 45,
 105,
 105,
 335,
 342,
 354,
 274,
 257,
 270,
 30,
 105,
 190,
 105,
 203,
 211,
 45,
 852,
 373,
 44,
 105,
 105,
 203,
 204,
 286040,
 1676,
 105,
 258,
 316,
 105,
 287,
 380,
 105,
 298,
 285,
 284,
 105,
 45,
 44,
 105,
 314,
 303,
 325,
 45,
 105,
 105,
 208,
 204,
 105,
 29,
 218,
 740,
 15722,
 105,
 373,
 306,
 308,
 224,
 229,
 267,
 225,
 295,
 288,
 272,
 297,
 311,
 305,
 295,
 105,
 511,
 239,
 105,
 5,
 288,
 287,
 308,
 284,
 299,
 380,
 105,
 357,
 360,
 359,
 478,
 308,
 1718,
 107,
 232,
 295,
 293,
 105,
 305,
 105,
 348,
 309,
 105,
 105,
 293,
 105,
 105,
 277,
 296,
 286,
 296,
 1177,
 266,
 105,
 45,
 236,
 298,
 105,
 227,
 216,
 218,
 352,
 347,
 44,
 105,
 0,
 105,
 236,
 105,
 234,
 354,
 311,
 323,
 105,
 301,
 105,
 1901,
 264,
 258,
 1975,
 255,
 326,
 330,
 332,
 45,
 280,
 105,
 331,
 309,
 317,
 222,
 223,
 234,
 221,
 105,
 276,
 46,
 46,
 105,
 231,
 232,
 225,
 222,
 105,
 36,
 227,
 229,
 238,
 229,
 237,
 308,
 296,
 300,
 297,
 199,
 273,
 267,
 300,
 298,
 323,
 327,
 247,
 105,
 105,
 350,
 104,
 1207,
 201,
 105,
 105,
 1356,
 304,
 105,
 105,
 223,
 237,
 235,
 105,
 849,
 302,
 303,
 195,
 308,
 2955,
 105,
 1219,
 358,
 245,
 319,
 265,
 231,
 320,
 105,
 44,
 103,
 43,
 822,
 43,
 308,
 240,
 105,
 210,
 328,
 320,
 105,
 346,
 105,
 105,
 230,
 105,
 334,
 710,
 105,
 105,
 1949,
 1810,
 1407,
 1244,
 44,
 674,
 293,
 294,
 294,
 289,
 105,
 8766,
 1308,
 241,
 249,
 105,
 45,
 105,
 253,
 105,
 237,
 2362,
 43,
 2943,
 2969,
 1562,
 57164,
 105,
 261,
 316,
 314,
 285,
 105,
 30,
 105,
 358,
 105,
 105,
 305,
 298,
 294,
 356,
 235,
 5862,
 105,
 258,
 323,
 324,
 105,
 45,
 334,
 347,
 351,
 264,
 1105,
 45,
 302,
 303,
 95,
 105,
 340,
 343,
 305,
 170,
 105,
 45,
 0,
 238,
 105,
 308,
 307,
 320,
 368,
 318,
 105,
 297,
 293,
 299,
 297,
 834,
 244,
 307,
 309,
 318,
 736,
 236,
 105,
 105,
 199,
 0,
 105,
 323,
 105,
 105,
 105,
 1341,
 105,
 308,
 105,
 289,
 183,
 298,
 105,
 105,
 105,
 232,
 302,
 105,
 263,
 249,
 243,
 308,
 307,
 240,
 242,
 243,
 1570,
 299,
 324,
 326,
 105,
 44,
 187,
 188,
 263,
 241,
 105,
 359,
 369,
 15471,
 310,
 225,
 326,
 332,
 356,
 4721,
 296,
 297,
 299,
 298,
 310,
 356,
 300,
 298,
 105,
 327,
 303,
 105,
 188,
 196,
 214,
 163,
 245,
 105,
 277,
 297,
 297,
 105,
 105,
 105,
 188,
 236,
 56124,
 300,
 298,
 245,
 1517,
 236,
 308,
 105,
 361,
 358,
 192,
 192,
 363,
 363,
 323,
 326,
 314,
 105,
 327,
 329,
 105,
 105,
 309,
 329,
 105,
 337,
 268,
 31645608,
 336,
 105,
 232,
 202,
 42,
 42,
 42,
 42,
 42,
 205,
 205,
 203,
 240,
 310,
 205,
 206,
 105,
 257,
 327,
 42,
 42,
 42,
 42,
 81,
 34,
 42,
 45,
 42,
 42,
 42,
 13,
 42,
 353,
 216,
 42,
 209,
 202,
 206,
 34,
 42,
 507,
 42,
 220,
 358,
 194,
 168,
 225,
 144,
 342,
 35,
 105,
 285,
 180,
 34,
 170,
 183,
 228,
 222,
 34,
 202,
 200,
 204,
 148,
 105,
 276,
 278,
 30,
 229,
 288,
 105,
 243,
 240,
 242,
 248,
 105,
 105,
 240,
 208,
 105,
 105,
 203,
 209,
 206,
 105,
 105,
 216,
 205,
 209,
 209,
 148,
 266,
 258,
 289,
 188,
 205,
 216,
 203,
 205,
 222,
 207,
 211,
 207,
 339,
 334,
 239,
 286,
 249,
 243,
 253,
 105,
 218,
 207,
 221,
 210,
 340,
 317,
 235,
 355,
 285,
 199,
 15722,
 105,
 181,
 105,
 1955,
 44,
 183,
 180,
 44,
 681,
 105,
 105,
 105,
 143,
 105,
 199,
 105,
 46,
 334,
 339,
 230,
 286,
 318,
 299,
 7658,
 105,
 292,
 229,
 232,
 229,
 233,
 1051,
 105,
 105,
 266,
 271,
 874,
 44,
 42,
 357,
 338,
 392,
 103,
 222,
 45,
 45,
 42,
 45,
 45,
 258,
 257,
 319,
 274,
 271,
 319,
 336,
 332,
 390,
 210,
 105,
 292,
 163,
 335,
 341,
 105,
 260,
 265,
 42,
 105,
 105,
 44,
 210,
 105,
 1598,
 344,
 318,
 802,
 330,
 332,
 332,
 42,
 224,
 105,
 105,
 30,
 1396,
 305,
 214,
 251,
 159,
 195,
 105,
 1262796,
 13,
 306,
 105,
 341,
 341,
 344,
 214,
 252,
 868,
 105,
 234,
 105,
 105,
 220,
 219,
 216,
 235,
 221,
 213,
 304,
 9,
 239,
 105,
 44,
 298,
 1430,
 340,
 105,
 1993,
 162,
 305,
 242,
 105,
 210,
 105,
 190,
 6932,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 1032,
 ...]

In [30]:
df['SRCBY'] = df.src_bytes.map({105:'SRC_BY_AB_100',29:'SRC_BY_BL_50',223:'SRC_BY_AB_200',230:'SRC_BY_AB_200',
                                3170:'SRC_BY_AB_3000',      297:'SRC_BY_AB_200',
291:'SRC_BY_AB_200',      295:'SRC_BY_AB_200',      268:'SRC_BY_AB_200',      227:'SRC_BY_AB_200',
                                222:'SRC_BY_AB_200',      740:'SRC_BY_AB_700',
          35195:'SRC_BY_AB_30000',     8325:'SRC_BY_AB_8000',      559:'SRC_BY_AB_500',      317:'SRC_BY_AB_300', 
                                1661:'SRC_BY_AB_1000',      232:'SRC_BY_AB_200',
            322:'SRC_BY_AB_300',      321:'SRC_BY_AB_300',      234:'SRC_BY_AB_200',      218:'SRC_BY_AB_200',
                                216:'SRC_BY_AB_200',      615:'SRC_BY_AB_600',
            312:'SRC_BY_AB_300',      307:'SRC_BY_AB_300',      246:'SRC_BY_AB_200',      245:'SRC_BY_AB_200', 
                                908:'SRC_BY_AB_900',      235:'SRC_BY_AB_200',
            249:'SRC_BY_AB_1000',      243:'SRC_BY_AB_200',      236:'SRC_BY_AB_200',      237:'SRC_BY_AB_200',
                                240:'SRC_BY_AB_200',      315:'SRC_BY_AB_300',
            313:'SRC_BY_AB_300',     1018:'SRC_BY_AB_1000',     1145:'SRC_BY_AB_1000',      244:'SRC_BY_AB_200',
                                275:'SRC_BY_AB_200',      247:'SRC_BY_AB_200',
            884:'SRC_BY_AB_800',      854:'SRC_BY_AB_800',       30:'SRC_BY_BL_50',       45:'SRC_BY_BL_50', 
                                1625:'SRC_BY_AB_1000',     1214:'SRC_BY_AB_1000',
            299:'SRC_BY_AB_200',      252:'SRC_BY_AB_200',       43:'SRC_BY_BL_50',      859:'SRC_BY_AB_800',
                                764:'SRC_BY_AB_700',    15722:'SRC_BY_AB_10000',
            151:'SRC_BY_AB_100',       44:'SRC_BY_BL_50',      765:'SRC_BY_AB_700',     2229:'SRC_BY_AB_2000',
                                294:'SRC_BY_AB_200',      305:'SRC_BY_AB_300',
            286:'SRC_BY_AB_200',      278:'SRC_BY_AB_200',      296:'SRC_BY_AB_200',      323:'SRC_BY_AB_300',
                                340:'SRC_BY_AB_300',        9:'SRC_BY_BL_50',
           1483:'SRC_BY_AB_1000',      910:'SRC_BY_AB_900',      224:'SRC_BY_AB_200',      163:'SRC_BY_AB_100', 
                                289:'SRC_BY_AB_200',       46:'SRC_BY_BL_50',
            192:'SRC_BY_AB_100',      335:'SRC_BY_AB_300',      342:'SRC_BY_AB_300',      354:'SRC_BY_AB_300', 
                                274:'SRC_BY_AB_200',      257:'SRC_BY_AB_200',
            270:'SRC_BY_AB_200',      190:'SRC_BY_AB_100',      203:'SRC_BY_AB_200',      211:'SRC_BY_AB_200', 
                                852:'SRC_BY_AB_800',      373:'SRC_BY_AB_300',
            204:'SRC_BY_AB_200',   286040:'SRC_BY_AB_200000',     1676:'SRC_BY_AB_1000',      258:'SRC_BY_AB_200',
                                316:'SRC_BY_AB_300',      287:'SRC_BY_AB_200',
            380:'SRC_BY_AB_300',      298:'SRC_BY_AB_200',      285:'SRC_BY_AB_200',      284:'SRC_BY_AB_200', 
                                314:'SRC_BY_AB_300',      303:'SRC_BY_AB_300',
            325:'SRC_BY_AB_300',      208:'SRC_BY_AB_200',      306:'SRC_BY_AB_300',      308:'SRC_BY_AB_300', 
                                229:'SRC_BY_AB_200',      267:'SRC_BY_AB_200',
            225:'SRC_BY_AB_200',      288:'SRC_BY_AB_200',      272:'SRC_BY_AB_200',      311:'SRC_BY_AB_300', 
                                511:'SRC_BY_AB_500',      239:'SRC_BY_AB_200',
              5:'SRC_BY_BL_50',      357:'SRC_BY_AB_300',      360:'SRC_BY_AB_300',      359:'SRC_BY_AB_300',
                                478:'SRC_BY_AB_400',     1718:'SRC_BY_AB_1000',
            107:'SRC_BY_AB_100',      293:'SRC_BY_AB_200',      348:'SRC_BY_AB_300',      309:'SRC_BY_AB_300',
                                277:'SRC_BY_AB_200',     1177:'SRC_BY_AB_1000',
            266:'SRC_BY_AB_200',      352:'SRC_BY_AB_300',      347:'SRC_BY_AB_300',        0:'SRC_BY_BL_50', 
                                301:'SRC_BY_AB_300',     1901:'SRC_BY_AB_1000',
            264:'SRC_BY_AB_200',     1975:'SRC_BY_AB_1000',      255:'SRC_BY_AB_200',      326:'SRC_BY_AB_300', 
                                330:'SRC_BY_AB_300',      332:'SRC_BY_AB_300',
            280:'SRC_BY_AB_200',      331:'SRC_BY_AB_300',      221:'SRC_BY_AB_200',      276:'SRC_BY_AB_200', 
                                231:'SRC_BY_AB_200',       36:'SRC_BY_BL_50',
            238:'SRC_BY_AB_200',      300:'SRC_BY_AB_300',      199:'SRC_BY_AB_100',      273:'SRC_BY_AB_200', 
                                327:'SRC_BY_AB_300',      350:'SRC_BY_AB_300',
            104:'SRC_BY_AB_100',     1207:'SRC_BY_AB_1000',      201:'SRC_BY_AB_200',     1356:'SRC_BY_AB_1000', 
                                304:'SRC_BY_AB_300',      849:'SRC_BY_AB_800',
            302:'SRC_BY_AB_300',      195:'SRC_BY_AB_100',     2955:'SRC_BY_AB_2000',     1219:'SRC_BY_AB_1000', 
                                358:'SRC_BY_AB_300',      319:'SRC_BY_AB_300',
            265:'SRC_BY_AB_200',      320:'SRC_BY_AB_300',      103:'SRC_BY_AB_100',      822:'SRC_BY_AB_800', 
                                210:'SRC_BY_AB_200',      328:'SRC_BY_AB_300',
            346:'SRC_BY_AB_300',      334:'SRC_BY_AB_300',      710:'SRC_BY_AB_700',     1949:'SRC_BY_AB_1000', 
                                1810:'SRC_BY_AB_1000',     1407:'SRC_BY_AB_1000',
           1244:'SRC_BY_AB_1000',      674:'SRC_BY_AB_600',     8766:'SRC_BY_AB_8000',     1308:'SRC_BY_AB_1000',
                                241:'SRC_BY_AB_200',      253:'SRC_BY_AB_200',
           2362:'SRC_BY_AB_2000',     2943:'SRC_BY_AB_2000',     2969:'SRC_BY_AB_2000',     1562:'SRC_BY_AB_1000', 
                                57164:'SRC_BY_AB_50000',      261:'SRC_BY_AB_200',
            356:'SRC_BY_AB_300',     5862:'SRC_BY_AB_5000',      324:'SRC_BY_AB_300',      351:'SRC_BY_AB_300', 
                                1105:'SRC_BY_AB_1000',       95:'SRC_BY_BL_50',
            343:'SRC_BY_AB_300',      170:'SRC_BY_AB_100',      368:'SRC_BY_AB_300',      318:'SRC_BY_AB_300', 
                                834:'SRC_BY_AB_800',      736:'SRC_BY_AB_700',
           1341:'SRC_BY_AB_1000',      183:'SRC_BY_AB_100',      263:'SRC_BY_AB_200',      242:'SRC_BY_AB_200', 
                                1570:'SRC_BY_AB_1000',      187:'SRC_BY_AB_100',
            188:'SRC_BY_AB_100',      369:'SRC_BY_AB_300',    15471:'SRC_BY_AB_10000',      310:'SRC_BY_AB_300',
                                4721:'SRC_BY_AB_4000',      196:'SRC_BY_AB_100',
            214:'SRC_BY_AB_200',    56124:'SRC_BY_AB_50000',     1517:'SRC_BY_AB_1000',      361:'SRC_BY_AB_300', 
                                363:'SRC_BY_AB_300',      329:'SRC_BY_AB_300',
            337:'SRC_BY_AB_300', 31645608:'SRC_BY_AB_30000000',      336:'SRC_BY_AB_300',      202:'SRC_BY_AB_200', 
                                42:'SRC_BY_BL_50',      205:'SRC_BY_AB_200',
            206:'SRC_BY_AB_200',       81:'SRC_BY_AB_100',       34:'SRC_BY_BL_50',       13:'SRC_BY_BL_50',  
                                353:'SRC_BY_AB_300',      209:'SRC_BY_AB_200',
            507:'SRC_BY_AB_500',      220:'SRC_BY_AB_200',      194:'SRC_BY_AB_100',      168:'SRC_BY_AB_100', 
                                144:'SRC_BY_AB_100',       35:'SRC_BY_BL_50',
            180:'SRC_BY_AB_100',      228:'SRC_BY_AB_200',      200:'SRC_BY_AB_200',      148:'SRC_BY_AB_100', 
                                248:'SRC_BY_AB_200',      207:'SRC_BY_AB_200',
            339:'SRC_BY_AB_300',      355:'SRC_BY_AB_300',      181:'SRC_BY_AB_100',     1955:'SRC_BY_AB_1000',
                                681:'SRC_BY_AB_600',      143:'SRC_BY_AB_100',
           7658:'SRC_BY_AB_7000',      292:'SRC_BY_AB_200',      233:'SRC_BY_AB_200',     1051:'SRC_BY_AB_1000', 
                                271:'SRC_BY_AB_200',      874:'SRC_BY_AB_800',
            338:'SRC_BY_AB_300',      392:'SRC_BY_AB_300',      390:'SRC_BY_AB_300',      341:'SRC_BY_AB_300',
                                260:'SRC_BY_AB_200',     1598:'SRC_BY_AB_1000',
            344:'SRC_BY_AB_300',      802:'SRC_BY_AB_800',     1396:'SRC_BY_AB_1000',      251:'SRC_BY_AB_200',
                                159:'SRC_BY_AB_100',  1262796:'SRC_BY_AB_1000000',
            868:'SRC_BY_AB_800',      219:'SRC_BY_AB_200',      213:'SRC_BY_AB_200',     1430:'SRC_BY_AB_1000', 
                                1993:'SRC_BY_AB_1000',      162:'SRC_BY_AB_100',
           6932:'SRC_BY_AB_6000',     1032:'SRC_BY_AB_1000',      146:'SRC_BY_AB_100',     1026:'SRC_BY_AB_1000', 
                                212:'SRC_BY_AB_200',      215:'SRC_BY_AB_200',
            254:'SRC_BY_AB_200',       18:'SRC_BY_BL_50',      217:'SRC_BY_AB_200',     1616:'SRC_BY_AB_1000', 
                                158:'SRC_BY_AB_100',     1022:'SRC_BY_AB_1000',
            193:'SRC_BY_AB_100',     1275:'SRC_BY_AB_1000',      262:'SRC_BY_AB_200',     1162:'SRC_BY_AB_1000',
                                1256:'SRC_BY_AB_1000',      184:'SRC_BY_AB_100',
           1205:'SRC_BY_AB_1000',      226:'SRC_BY_AB_200',      256:'SRC_BY_AB_200',       40:'SRC_BY_BL_50',
                                367:'SRC_BY_AB_300',     1670:'SRC_BY_AB_1000',
           2197:'SRC_BY_AB_2000',      164:'SRC_BY_AB_100',      282:'SRC_BY_AB_200',      101:'SRC_BY_AB_100', 
                                1456:'SRC_BY_AB_1000',      152:'SRC_BY_AB_100',
            366:'SRC_BY_AB_300',     1268:'SRC_BY_AB_1000',    12773:'SRC_BY_AB_10000',     1960:'SRC_BY_AB_1000', 
                                1029:'SRC_BY_AB_1000',     1843:'SRC_BY_AB_1000',
            259:'SRC_BY_AB_200',     2434:'SRC_BY_AB_2000',    61712:'SRC_BY_AB_60000',     1094:'SRC_BY_AB_1000', 
                                876:'SRC_BY_AB_800',      126:'SRC_BY_AB_100',
             10:'SRC_BY_BL_50',   139508:'SRC_BY_AB_100000',      505:'SRC_BY_AB_500',     1485:'SRC_BY_AB_1000',
                                174:'SRC_BY_AB_100',     1028:'SRC_BY_AB_1000',
            
            186:'SRC_BY_AB_100',      841:'SRC_BY_AB_800',     2113:'SRC_BY_AB_2000',      147:'SRC_BY_AB_100', 
                                4300:'SRC_BY_AB_4000',     3430:'SRC_BY_AB_3000',
            197:'SRC_BY_AB_100',     1176:'SRC_BY_AB_1000',      281:'SRC_BY_AB_200',     1288:'SRC_BY_AB_1000',
                                198:'SRC_BY_AB_100',      157:'SRC_BY_AB_100',
           1481:'SRC_BY_AB_1000',     1035:'SRC_BY_AB_1000',     6095:'SRC_BY_AB_6000',      885:'SRC_BY_AB_800',
                                1139:'SRC_BY_AB_1000',      812:'SRC_BY_AB_800',
           1816:'SRC_BY_AB_1000',      755:'SRC_BY_AB_700',     1092:'SRC_BY_AB_1000',      269:'SRC_BY_AB_200', 
                                599:'SRC_BY_AB_500',     3061:'SRC_BY_AB_3000',
           1419:'SRC_BY_AB_1000',      191:'SRC_BY_AB_100',      388:'SRC_BY_AB_300',      385:'SRC_BY_AB_300',
                                382:'SRC_BY_AB_300',        8:'SRC_BY_BL_50',
            703:'SRC_BY_AB_700',      176:'SRC_BY_AB_100',     1266:'SRC_BY_AB_1000',      773:'SRC_BY_AB_700', 
                                4746:'SRC_BY_AB_4000',      708:'SRC_BY_AB_700',
          11629:'SRC_BY_AB_10000',      167:'SRC_BY_AB_100',      290:'SRC_BY_AB_200',      934:'SRC_BY_AB_900', 
                                2477:'SRC_BY_AB_2000',     1315:'SRC_BY_AB_1000',
            182:'SRC_BY_AB_100',      687:'SRC_BY_AB_600',      995:'SRC_BY_AB_900',     1312:'SRC_BY_AB_1000', 
                                777:'SRC_BY_AB_700',    16225:'SRC_BY_AB_10000',
           4485:'SRC_BY_AB_4000',      154:'SRC_BY_AB_100',       17:'SRC_BY_BL_50',      861:'SRC_BY_AB_800', 
                                1438:'SRC_BY_AB_1000',      279:'SRC_BY_AB_200',
            386:'SRC_BY_AB_300',     1073:'SRC_BY_AB_1000',      333:'SRC_BY_AB_300',      569:'SRC_BY_AB_500', 
                                166:'SRC_BY_AB_100',       26:'SRC_BY_BL_50',
             74:'SRC_BY_AB_100',       20:'SRC_BY_BL_50',     2680:'SRC_BY_AB_2000',        1:'SRC_BY_BL_50', 
                                374:'SRC_BY_AB_300',     1367:'SRC_BY_AB_1000',
            171:'SRC_BY_AB_100',     7378:'SRC_BY_AB_7000',      129:'SRC_BY_AB_100',      160:'SRC_BY_AB_100', 
                                776:'SRC_BY_AB_700',      250:'SRC_BY_AB_200',
            942:'SRC_BY_AB_900',      178:'SRC_BY_AB_100',      665:'SRC_BY_AB_600',     1376:'SRC_BY_AB_1000', 
                                59:'SRC_BY_AB_100',    10261:'SRC_BY_AB_10000',
            169:'SRC_BY_AB_100',     1216:'SRC_BY_AB_1000',     2442:'SRC_BY_AB_2000',      503:'SRC_BY_AB_500', 
                                516:'SRC_BY_AB_500',      925:'SRC_BY_AB_900',
            349:'SRC_BY_AB_300',      494:'SRC_BY_AB_400',      345:'SRC_BY_AB_300',     1137:'SRC_BY_AB_1000', 
                                362:'SRC_BY_AB_300',       33:'SRC_BY_BL_50',
            916:'SRC_BY_AB_900',      641:'SRC_BY_AB_500',    12241:'SRC_BY_AB_10000',      177:'SRC_BY_AB_100', 
                                179:'SRC_BY_AB_100',     1043:'SRC_BY_AB_1000',
           2130:'SRC_BY_AB_2000',     1013:'SRC_BY_AB_1000',     5720:'SRC_BY_AB_5000',      814:'SRC_BY_AB_100', 
                                141:'SRC_BY_AB_100',      189:'SRC_BY_AB_100',
            185:'SRC_BY_AB_100',     1313:'SRC_BY_AB_1000',     1025:'SRC_BY_AB_1000',      155:'SRC_BY_AB_100', 
                                175:'SRC_BY_AB_100',     1020:'SRC_BY_AB_1000',
          13239:'SRC_BY_AB_10000',       31:'SRC_BY_BL_50',     3894:'SRC_BY_AB_3000',       38:'SRC_BY_BL_50',
                                501760:'SRC_BY_AB_500000',     2149:'SRC_BY_AB_2000',
           3594:'SRC_BY_AB_3000',      165:'SRC_BY_AB_100',      172:'SRC_BY_AB_100',     4062:'SRC_BY_AB_4000', 
                                3456:'SRC_BY_AB_3000',     1310:'SRC_BY_AB_1000',
           2300:'SRC_BY_AB_2000',      483:'SRC_BY_AB_400',     7422:'SRC_BY_AB_7000',     1416:'SRC_BY_AB_1000', 
                                14080:'SRC_BY_AB_10000',      662:'SRC_BY_AB_600',
           4543:'SRC_BY_AB_4000',      872:'SRC_BY_AB_800',    12672:'SRC_BY_AB_10000',    12963:'SRC_BY_AB_10000', 
                                630:'SRC_BY_AB_600',     2162:'SRC_BY_AB_2000',
            858:'SRC_BY_AB_800',     1387:'SRC_BY_AB_1000',      471:'SRC_BY_AB_400',      475:'SRC_BY_AB_400', 
                                173:'SRC_BY_AB_100',      678:'SRC_BY_AB_600',
            140:'SRC_BY_AB_100',      801:'SRC_BY_AB_800',      153:'SRC_BY_AB_100',      150:'SRC_BY_AB_100',
                                149:'SRC_BY_AB_100',      850:'SRC_BY_AB_800',
           5399:'SRC_BY_AB_5000',     2275:'SRC_BY_AB_2000',      911:'SRC_BY_AB_900',     1448:'SRC_BY_AB_1000',
                                1082:'SRC_BY_AB_1000',      381:'SRC_BY_AB_300',
           1459:'SRC_BY_AB_1000',     1111:'SRC_BY_AB_1000',     1465:'SRC_BY_AB_1000',      774:'SRC_BY_AB_700', 
                                3916:'SRC_BY_AB_3000',      998:'SRC_BY_AB_900',
            161:'SRC_BY_AB_100',      283:'SRC_BY_AB_200',     1626:'SRC_BY_AB_1000',     1041:'SRC_BY_AB_1000',  
                                3625:'SRC_BY_AB_3000',      402:'SRC_BY_AB_400',
            399:'SRC_BY_AB_300',      479:'SRC_BY_AB_400',      142:'SRC_BY_AB_100',      448:'SRC_BY_AB_400', 
                                1294:'SRC_BY_AB_1000',      447:'SRC_BY_AB_400',
          48181:'SRC_BY_AB_40000',      442:'SRC_BY_AB_400',     2111:'SRC_BY_AB_2000',     1030:'SRC_BY_AB_1000', 
                                523:'SRC_BY_AB_500',      832:'SRC_BY_AB_800',
            870:'SRC_BY_AB_800',      869:'SRC_BY_AB_800',      786:'SRC_BY_AB_700',      785:'SRC_BY_AB_700', 
                                48:'SRC_BY_BL_50',      377:'SRC_BY_AB_300',
           3160:'SRC_BY_AB_3000',     1874:'SRC_BY_AB_1000',      383:'SRC_BY_AB_300',      370:'SRC_BY_AB_300', 
                                699:'SRC_BY_AB_600',      985:'SRC_BY_AB_900',
           3650:'SRC_BY_AB_3000',     5050:'SRC_BY_AB_5000',     1057:'SRC_BY_AB_1000',     1190:'SRC_BY_AB_1000', 
                                2351:'SRC_BY_AB_2000',     1264:'SRC_BY_AB_1000',
           1892:'SRC_BY_AB_1000',     9667:'SRC_BY_AB_9000',     1347:'SRC_BY_AB_1000',     1930:'SRC_BY_AB_1000', 
                                794:'SRC_BY_AB_700',     1405:'SRC_BY_AB_1000',
           1008:'SRC_BY_AB_1000',     1462:'SRC_BY_AB_1000',     7233:'SRC_BY_AB_7000',      899:'SRC_BY_AB_800', 
                                890:'SRC_BY_AB_800',      987:'SRC_BY_AB_900',
           1113:'SRC_BY_AB_1000',     1188:'SRC_BY_AB_1000',     1662:'SRC_BY_AB_1000',     1677:'SRC_BY_AB_1000', 
                                1421:'SRC_BY_AB_1000',      517:'SRC_BY_AB_500',
           3690:'SRC_BY_AB_3000',    10073:'SRC_BY_AB_10000',     1688:'SRC_BY_AB_1000',      864:'SRC_BY_AB_800', 
                                613:'SRC_BY_AB_600',     1339:'SRC_BY_AB_1000',
            742:'SRC_BY_AB_700',     1772:'SRC_BY_AB_1000',     2259:'SRC_BY_AB_2000',     1417:'SRC_BY_AB_1000', 
                                1023:'SRC_BY_AB_1000',     1699:'SRC_BY_AB_1000',
           2652:'SRC_BY_AB_2000',      877:'SRC_BY_AB_800',      830:'SRC_BY_AB_800',       37:'SRC_BY_BL_50', 
                                722:'SRC_BY_AB_700',     1769:'SRC_BY_AB_1000',
           1766:'SRC_BY_AB_1000',      949:'SRC_BY_AB_900',     6259:'SRC_BY_AB_6000',      951:'SRC_BY_AB_900', 
                                2207:'SRC_BY_AB_2000',    14096:'SRC_BY_AB_10000',
           1269:'SRC_BY_AB_1000',    13334:'SRC_BY_AB_1000',     1011:'SRC_BY_AB_1000',     1851:'SRC_BY_AB_1000',  
                                2574:'SRC_BY_AB_2000',     7012:'SRC_BY_AB_7000',
           8173:'SRC_BY_AB_8000',     1390:'SRC_BY_AB_1000',      863:'SRC_BY_AB_800',     1281:'SRC_BY_AB_1000',  
                                1536:'SRC_BY_AB_1000',      760:'SRC_BY_AB_700',
           1433:'SRC_BY_AB_1000',     1434:'SRC_BY_AB_1000',     1539:'SRC_BY_AB_1000',     3909:'SRC_BY_AB_3000', 
                                3109:'SRC_BY_AB_3000',     3149:'SRC_BY_AB_3000',
            365:'SRC_BY_AB_300',     2190:'SRC_BY_AB_2000',     7191:'SRC_BY_AB_7000',      749:'SRC_BY_AB_700', 
                                1349:'SRC_BY_AB_1000',     1222:'SRC_BY_AB_1000',
            550:'SRC_BY_AB_500',     2776:'SRC_BY_AB_2000',     2452:'SRC_BY_AB_2000',       97:'SRC_BY_AB_100', 
                                1935:'SRC_BY_AB_1000',      912:'SRC_BY_AB_900',
            892:'SRC_BY_AB_800',     1531:'SRC_BY_AB_1000',      139:'SRC_BY_AB_100',      371:'SRC_BY_AB_300', 
                                7162:'SRC_BY_AB_7000',       11:'SRC_BY_BL_50',
           1342:'SRC_BY_AB_1000',     1588:'SRC_BY_AB_1000',      579:'SRC_BY_AB_500',    20879:'SRC_BY_AB_20000', 
                                375:'SRC_BY_AB_300',      933:'SRC_BY_AB_900',
           1564:'SRC_BY_AB_1000',      389:'SRC_BY_AB_300',     1480:'SRC_BY_AB_1000',     1961:'SRC_BY_AB_1000', 
                                4542:'SRC_BY_AB_4000',      567:'SRC_BY_AB_500',
           2625:'SRC_BY_AB_2000',     2513:'SRC_BY_AB_2000',     1100:'SRC_BY_AB_1000',     2288:'SRC_BY_AB_2000', 
                                497:'SRC_BY_AB_400',     2956:'SRC_BY_AB_2000',
            809:'SRC_BY_AB_800',     1830:'SRC_BY_AB_1000',     3805:'SRC_BY_AB_3000',     1167:'SRC_BY_AB_1000', 
                                2101:'SRC_BY_AB_2000',     1566:'SRC_BY_AB_1000',
           1317:'SRC_BY_AB_1000',     6317:'SRC_BY_AB_6000',        6:'SRC_BY_BL_50',      394:'SRC_BY_AB_300',  
                                84:'SRC_BY_BL_50',      797:'SRC_BY_AB_700',
            372:'SRC_BY_AB_300',       58:'SRC_BY_AB_100',     4753:'SRC_BY_AB_4000',     1576:'SRC_BY_AB_1000',  
                                1175:'SRC_BY_AB_1000',     1722:'SRC_BY_AB_1000',
           5475:'SRC_BY_AB_5000',     2291:'SRC_BY_AB_2000',      682:'SRC_BY_AB_600',     1005:'SRC_BY_AB_1000', 
                                7:'SRC_BY_BL_50',      156:'SRC_BY_AB_100',
           1278:'SRC_BY_AB_1000',      994:'SRC_BY_AB_900',      145:'SRC_BY_AB_100',     1206:'SRC_BY_AB_1000', 
                                659:'SRC_BY_AB_600',      945:'SRC_BY_AB_900',
           3273:'SRC_BY_AB_3000',      775:'SRC_BY_AB_700',      564:'SRC_BY_AB_500',    57964:'SRC_BY_AB_50000', 
                                60884:'SRC_BY_AB_60000',    59424:'SRC_BY_AB_50000',
          53584:'SRC_BY_AB_50000',    62344:'SRC_BY_AB_60000',    81324:'SRC_BY_AB_80000',    90084:'SRC_BY_AB_90000', 
                                87164:'SRC_BY_AB_80000',    65264:'SRC_BY_AB_60000',
          63804:'SRC_BY_AB_60000',    85704:'SRC_BY_AB_80000',    88624:'SRC_BY_AB_80000',    75484:'SRC_BY_AB_70000', 
                                76944:'SRC_BY_AB_70000',    56504:'SRC_BY_AB_50000',
          12704:'SRC_BY_AB_10000',    78404:'SRC_BY_AB_70000',    17084:'SRC_BY_AB_10000',    55044:'SRC_BY_AB_50000',
                                3944:'SRC_BY_AB_3000',     2484:'SRC_BY_AB_2000',
           8324:'SRC_BY_AB_8000',    21464:'SRC_BY_AB_20000',     6864:'SRC_BY_AB_6000',    25844:'SRC_BY_AB_20000', 
                                1024:'SRC_BY_AB_1000',    74024:'SRC_BY_AB_70000',
          72564:'SRC_BY_AB_70000',    58624:'SRC_BY_AB_50000',    75904:'SRC_BY_AB_70000',    73024:'SRC_BY_AB_70000', 
                                55744:'SRC_BY_AB_50000',    61504:'SRC_BY_AB_60000',
          74464:'SRC_BY_AB_70000',    49984:'SRC_BY_AB_40000',     9664:'SRC_BY_AB_9000',    60064:'SRC_BY_AB_60000', 
                                57184:'SRC_BY_AB_50000',    77344:'SRC_BY_AB_70000',
          37024:'SRC_BY_AB_30000',    25504:'SRC_BY_AB_20000',    24064:'SRC_BY_AB_20000',    71584:'SRC_BY_AB_70000',
                                3904:'SRC_BY_AB_3000',    68704:'SRC_BY_AB_60000',
          70144:'SRC_BY_AB_70000',    54304:'SRC_BY_AB_50000',    44224:'SRC_BY_AB_40000',     2464:'SRC_BY_AB_2000',   
                                7324:'SRC_BY_AB_7000',     2263:'SRC_BY_AB_2000',
           2783:'SRC_BY_AB_2000',   2742:'SRC_BY_AB_2000'})

In [31]:
df=df.dropna()

In [32]:
df['SRCBY'].unique()

array(['SRC_BY_AB_100', 'SRC_BY_BL_50', 'SRC_BY_AB_200', 'SRC_BY_AB_3000',
       'SRC_BY_AB_700', 'SRC_BY_AB_30000', 'SRC_BY_AB_8000',
       'SRC_BY_AB_500', 'SRC_BY_AB_300', 'SRC_BY_AB_1000',
       'SRC_BY_AB_600', 'SRC_BY_AB_900', 'SRC_BY_AB_800',
       'SRC_BY_AB_10000', 'SRC_BY_AB_2000', 'SRC_BY_AB_200000',
       'SRC_BY_AB_400', 'SRC_BY_AB_50000', 'SRC_BY_AB_5000',
       'SRC_BY_AB_4000', 'SRC_BY_AB_30000000', 'SRC_BY_AB_7000',
       'SRC_BY_AB_1000000', 'SRC_BY_AB_6000', 'SRC_BY_AB_60000',
       'SRC_BY_AB_100000', 'SRC_BY_AB_500000', 'SRC_BY_AB_40000',
       'SRC_BY_AB_9000', 'SRC_BY_AB_20000', 'SRC_BY_AB_80000',
       'SRC_BY_AB_90000', 'SRC_BY_AB_70000'], dtype=object)

In [33]:
df['SRC_BY_BL_50'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':1, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})

In [34]:
df['SRC_BY_AB_100'] = df.SRCBY.map({'SRC_BY_AB_100':1, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_200'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':1, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_3000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':1,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_700'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':1, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})

In [35]:
df['SRC_BY_AB_30000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':1, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_8000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':1,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_500'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':1, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_300'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':1, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})

In [36]:
df['SRC_BY_AB_1000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':1,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_600'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':1, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_900'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':1, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_800'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':1,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})

In [37]:
df['SRC_BY_AB_10000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':1, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_2000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':1, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_200000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':1,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_400'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':1, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})

In [38]:
df['SRC_BY_AB_50000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':1, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_5000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':1,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_4000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':1, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_30000000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':1,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_7000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':1,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_1000000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':1, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_6000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':1, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_60000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':1,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_100000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':1,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})

In [39]:
df['SRC_BY_AB_500000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':1, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_40000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':1,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_9000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':1, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_20000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':1, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_80000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':1,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_90000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':1, 'SRC_BY_AB_70000':0})
df['SRC_BY_AB_70000'] = df.SRCBY.map({'SRC_BY_AB_100':0, 'SRC_BY_BL_50':0, 'SRC_BY_AB_200':0, 'SRC_BY_AB_3000':0,
       'SRC_BY_AB_700':0, 'SRC_BY_AB_30000':0, 'SRC_BY_AB_8000':0,'SRC_BY_AB_500':0, 'SRC_BY_AB_300':0, 'SRC_BY_AB_1000':0,
       'SRC_BY_AB_600':0, 'SRC_BY_AB_900':0, 'SRC_BY_AB_800':0,'SRC_BY_AB_10000':0, 'SRC_BY_AB_2000':0, 'SRC_BY_AB_200000':0,
       'SRC_BY_AB_400':0, 'SRC_BY_AB_50000':0, 'SRC_BY_AB_5000':0,'SRC_BY_AB_4000':0, 'SRC_BY_AB_30000000':0,
        'SRC_BY_AB_7000':0,'SRC_BY_AB_1000000':0, 'SRC_BY_AB_6000':0, 'SRC_BY_AB_60000':0,'SRC_BY_AB_100000':0,
    'SRC_BY_AB_500000':0, 'SRC_BY_AB_40000':0,'SRC_BY_AB_9000':0, 'SRC_BY_AB_20000':0, 'SRC_BY_AB_80000':0,
                         'SRC_BY_AB_90000':0, 'SRC_BY_AB_70000':1})

In [40]:
del df['src_bytes']

In [41]:
df.columns

Index(['dst_bytes', 'Wrong_fragment', 'serror_rate', 'rerror_rate', 'class',
       'attack', 'Attack_Type', 'UDP', 'TCP', 'ICMP',
       ...
       'SRC_BY_AB_6000', 'SRC_BY_AB_60000', 'SRC_BY_AB_100000',
       'SRC_BY_AB_500000', 'SRC_BY_AB_40000', 'SRC_BY_AB_9000',
       'SRC_BY_AB_20000', 'SRC_BY_AB_80000', 'SRC_BY_AB_90000',
       'SRC_BY_AB_70000'],
      dtype='object', length=117)

In [42]:
list(df['dst_bytes'])

[146,
 146,
 146,
 146,
 146,
 146,
 0,
 146,
 146,
 185,
 146,
 260,
 146,
 146,
 329,
 13787,
 3542,
 753,
 146,
 146,
 9235,
 146,
 185,
 8841,
 19564,
 0,
 146,
 0,
 0,
 146,
 146,
 146,
 146,
 336,
 182,
 146,
 278,
 330,
 765,
 680,
 2060,
 14497,
 261,
 7504,
 0,
 677,
 146,
 1528,
 146,
 146,
 753,
 146,
 4199,
 146,
 330,
 146,
 2367,
 695,
 198,
 146,
 146,
 146,
 3817,
 2211,
 3665,
 675,
 662,
 2172,
 1528,
 5381,
 146,
 333,
 329,
 146,
 146,
 668,
 525,
 259,
 662,
 0,
 0,
 146,
 0,
 146,
 146,
 146,
 146,
 146,
 110,
 377,
 146,
 0,
 146,
 2178,
 1010,
 0,
 107,
 146,
 2586,
 329,
 0,
 0,
 146,
 45,
 332,
 112,
 325,
 146,
 115,
 481,
 44,
 938,
 289,
 1745,
 146,
 146,
 146,
 958,
 1731,
 938,
 921,
 3301,
 146,
 247,
 35,
 146,
 146,
 475,
 146,
 146,
 146,
 146,
 332,
 146,
 2006,
 20554,
 115,
 1401,
 283,
 188,
 1743,
 117,
 146,
 117,
 146,
 0,
 115,
 114,
 146,
 146,
 606,
 396,
 2650,
 349,
 9885,
 345,
 0,
 146,
 0,
 146,
 294,
 631,
 110,
 6787,
 412,
 115,
 146,
 145,
 294,
 2199,
 383476,
 333,
 146,
 1432,
 5141,
 146,
 4191,
 19012,
 146,
 321,
 5200,
 6924,
 146,
 110,
 113,
 146,
 3113,
 264,
 2026,
 115,
 146,
 146,
 2393,
 308,
 146,
 0,
 2219,
 0,
 0,
 146,
 412,
 3313,
 1512,
 799,
 1733,
 327,
 673,
 1549,
 371,
 22633,
 2427,
 379,
 1707,
 603,
 146,
 6839,
 285,
 146,
 27,
 391,
 1289,
 1713,
 292,
 273,
 19012,
 146,
 354,
 1053,
 821,
 6248,
 2521,
 327,
 407,
 193,
 603,
 2427,
 146,
 525,
 146,
 9189,
 741,
 146,
 146,
 2427,
 146,
 146,
 14274,
 2427,
 492,
 667,
 334,
 6104,
 146,
 110,
 431,
 1197,
 146,
 1574,
 382,
 1743,
 633,
 124,
 115,
 146,
 4,
 146,
 32473,
 146,
 6104,
 353,
 12502,
 873,
 146,
 4555,
 146,
 329,
 283,
 1812,
 406,
 372,
 468,
 1791,
 699,
 115,
 302,
 146,
 13166,
 603,
 1797,
 278,
 289,
 1745,
 675,
 146,
 810,
 117,
 117,
 146,
 1697,
 1850,
 283,
 897,
 146,
 101,
 452,
 188,
 197,
 1161,
 196,
 1549,
 402,
 1134,
 2427,
 17455,
 2348,
 524,
 1134,
 371,
 1193,
 3548,
 13425,
 146,
 146,
 821,
 403,
 401,
 4841,
 146,
 146,
 327,
 10022,
 146,
 146,
 938,
 196,
 194,
 146,
 325,
 3188,
 818,
 9571,
 2096,
 331,
 146,
 320,
 258,
 0,
 564,
 394,
 1034,
 1667,
 146,
 113,
 402,
 107,
 335,
 43,
 257,
 685,
 146,
 392,
 22145,
 1667,
 146,
 7969,
 146,
 146,
 1047,
 146,
 10572,
 334,
 146,
 146,
 473,
 340,
 331,
 411,
 115,
 327,
 770,
 396,
 16082,
 313,
 146,
 0,
 332,
 4378,
 753,
 146,
 115,
 146,
 16147,
 146,
 1047,
 329,
 107,
 482,
 330,
 0,
 35576,
 146,
 3973,
 1379,
 7873,
 903,
 146,
 0,
 146,
 1437,
 146,
 146,
 1850,
 188,
 675,
 1402,
 874,
 332,
 146,
 18718,
 775,
 1063,
 146,
 115,
 7344,
 6788,
 2093,
 2862,
 326,
 110,
 1193,
 5972,
 0,
 146,
 3331,
 7439,
 486,
 9392,
 146,
 110,
 4,
 26625,
 146,
 3060,
 342,
 407,
 14607,
 5064,
 146,
 64498,
 634,
 4897,
 306,
 332,
 1047,
 5381,
 1212,
 12341,
 330,
 1047,
 146,
 146,
 309,
 0,
 146,
 1587,
 146,
 146,
 146,
 375,
 146,
 9929,
 146,
 593,
 3855,
 2239,
 146,
 146,
 146,
 1047,
 3115,
 146,
 347,
 1573,
 3551,
 2156,
 1984,
 294,
 336,
 531,
 332,
 4058,
 430,
 241,
 146,
 44,
 2702,
 2199,
 4947,
 586,
 146,
 468,
 345,
 0,
 1587,
 588,
 2445,
 5893,
 2772,
 334,
 2443,
 753,
 1496,
 1047,
 3222,
 1359,
 3463,
 943,
 146,
 10624,
 3222,
 146,
 2702,
 631,
 753,
 16696,
 870,
 146,
 35014,
 1093,
 1372,
 146,
 146,
 146,
 308,
 520,
 17588,
 709,
 1030,
 870,
 388,
 1055,
 257,
 146,
 755,
 185,
 753,
 307,
 259,
 190,
 2427,
 2445,
 6924,
 146,
 664,
 1266,
 146,
 145,
 3222,
 4471,
 146,
 1212,
 9207,
 207796,
 3313,
 146,
 2698,
 3376,
 42,
 42,
 42,
 42,
 42,
 1965,
 770,
 321,
 9207,
 1512,
 3410,
 16082,
 146,
 8712,
 1565,
 42,
 42,
 42,
 42,
 0,
 34,
 42,
 45,
 42,
 42,
 42,
 39,
 42,
 1565,
 1850,
 42,
 673,
 1743,
 278,
 34,
 42,
 60530,
 42,
 1047,
 625,
 339,
 13141,
 6281,
 193,
 1011,
 100,
 146,
 25519,
 1797,
 34,
 9699,
 11200,
 300,
 6324,
 34,
 2863,
 382,
 634,
 1098,
 146,
 1398,
 1564,
 0,
 772,
 168,
 146,
 520,
 441,
 1809,
 283,
 146,
 146,
 2772,
 267,
 146,
 146,
 2863,
 306,
 675,
 146,
 146,
 1850,
 304,
 188,
 449,
 3713,
 1471,
 445,
 168,
 3913,
 304,
 1850,
 291,
 675,
 197,
 938,
 1429,
 291,
 1773,
 6989,
 6291,
 169,
 588,
 291,
 309,
 146,
 4904,
 291,
 196,
 2858,
 8557,
 402,
 2698,
 30327,
 25519,
 2034,
 0,
 146,
 11444,
 146,
 408,
 44,
 5247,
 1151,
 44,
 331,
 146,
 146,
 146,
 459,
 146,
 601,
 146,
 46,
 1930,
 1556,
 49759,
 6924,
 19075,
 3200,
 0,
 146,
 326,
 2153,
 3287,
 1567,
 1009,
 331,
 146,
 146,
 1302,
 799,
 333,
 115,
 42,
 247,
 3200,
 526,
 402,
 5338,
 114,
 114,
 42,
 114,
 114,
 4823,
 3582,
 4033,
 1326,
 755,
 181,
 1284,
 3200,
 526,
 13057,
 146,
 257,
 6045,
 674,
 1150,
 146,
 283,
 436,
 42,
 146,
 146,
 113,
 13057,
 146,
 329,
 5681,
 1466,
 330,
 2975,
 5190,
 1383,
 42,
 855,
 146,
 146,
 0,
 324,
 2507,
 1047,
 366,
 193,
 1227,
 146,
 15820,
 38,
 483,
 146,
 25080,
 638,
 2053,
 1734,
 272,
 339,
 146,
 2698,
 146,
 146,
 1047,
 820,
 990,
 866,
 12304,
 45263,
 483,
 37,
 3443,
 146,
 115,
 502,
 328,
 5683,
 146,
 392,
 3433,
 160,
 55605,
 146,
 392,
 146,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [43]:
df['DSTBY'] = df.dst_bytes.map({146:'DST_BY_AB_100',146:'DST_BY_AB_100',146:'DST_BY_AB_100',146:'DST_BY_AB_100',
 146:'DST_BY_AB_100',146:'DST_BY_AB_100',0:'DST_BY_BL_50',146:'DST_BY_AB_100',146:'DST_BY_AB_100',185:'DST_BY_AB_100',
146:'DST_BY_AB_100',260:'DST_BY_AB_200',146:'DST_BY_AB_100',146:'DST_BY_AB_100',329:'DST_BY_AB_300',13787:'DST_BY_AB_10000',
3542:'DST_BY_AB_3000',753:'DST_BY_AB_700',146:'DST_BY_AB_100',146:'DST_BY_AB_100',
9235:'DST_BY_AB_9000',146:'DST_BY_AB_100',185:'DST_BY_AB_100',8841:'DST_BY_AB_8000',
19564:'DST_BY_AB_10000',0:'DST_BY_BL_50',146:'DST_BY_AB_100',0:'DST_BY_BL_50',0:'DST_BY_BL_50',146:'DST_BY_AB_100',
146:'DST_BY_AB_100',146:'DST_BY_AB_100',146:'DST_BY_AB_100',336:'DST_BY_AB_300',182:'DST_BY_AB_100',146:'DST_BY_AB_100',
278:'DST_BY_AB_200',330:'DST_BY_AB_300',765:'DST_BY_AB_700',680:'DST_BY_AB_600',2060:'DST_BY_AB_2000',14497:'DST_BY_AB_10000',
261:'DST_BY_AB_200',7504:'DST_BY_AB_7000',0:'DST_BY_BL_50',677:'DST_BY_AB_600',146:'DST_BY_AB_100',1528:'DST_BY_AB_1000',
146:'DST_BY_AB_100',146:'DST_BY_AB_100',753:'DST_BY_AB_700',146:'DST_BY_AB_100',4199:'DST_BY_AB_4000',146:'DST_BY_AB_100',
330:'DST_BY_AB_300',146:'DST_BY_AB_100',2367:'DST_BY_AB_2000',695:'DST_BY_AB_600',198:'DST_BY_AB_100',
146:'DST_BY_AB_100',146:'DST_BY_AB_100',146:'DST_BY_AB_100',3817:'DST_BY_AB_3000',2211:'DST_BY_AB_2000',3665:'DST_BY_AB_3000',
675:'DST_BY_AB_600',662:'DST_BY_AB_600',2172:'DST_BY_AB_2000',1528:'DST_BY_AB_1000',5381:'DST_BY_AB_5000',146:'DST_BY_AB_100',
333:'DST_BY_AB_300',329:'DST_BY_AB_300',146:'DST_BY_AB_100',146:'DST_BY_AB_100',668:'DST_BY_AB_600',525:'DST_BY_AB_500',
259:'DST_BY_AB_200',662:'DST_BY_AB_600',0:'DST_BY_BL_50',0:'DST_BY_BL_50',146:'DST_BY_AB_100',0:'DST_BY_BL_50',
146:'DST_BY_AB_100',146:'DST_BY_AB_100',146:'DST_BY_AB_100',146:'DST_BY_AB_100',146:'DST_BY_AB_100',110:'DST_BY_AB_100',
377:'DST_BY_AB_300',146:'DST_BY_AB_100',0:'DST_BY_BL_50',146:'DST_BY_AB_100',2178:'DST_BY_AB_100',1010:'DST_BY_AB_100',
0:'DST_BY_BL_50',107:'DST_BY_AB_100',146:'DST_BY_AB_100',2586:'DST_BY_AB_2000',329:'DST_BY_AB_300',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',146:'DST_BY_AB_100',45:'DST_BY_BL_50',332:'DST_BY_AB_300',112:'DST_BY_AB_100',
325:'DST_BY_AB_300',146:'DST_BY_AB_100',115:'DST_BY_AB_100',481:'DST_BY_AB_400',44:'DST_BY_BL_50',938:'DST_BY_AB_900',
289:'DST_BY_AB_200',1745:'DST_BY_AB_1000',146:'DST_BY_AB_100',146:'DST_BY_AB_100',146:'DST_BY_AB_100',958:'DST_BY_AB_900',
1731:'DST_BY_AB_1000',938:'DST_BY_AB_900',921:'DST_BY_AB_900',3301:'DST_BY_AB_3000',146:'DST_BY_AB_100',247:'DST_BY_AB_200',
35:'DST_BY_BL_50',146:'DST_BY_AB_100',146:'DST_BY_AB_100',475:'DST_BY_AB_400',146:'DST_BY_AB_100',
146:'DST_BY_AB_100',146:'DST_BY_AB_100',146:'DST_BY_AB_100',332:'DST_BY_AB_300',146:'DST_BY_AB_100',2006:'DST_BY_AB_2000',
20554:'DST_BY_AB_2000',115:'DST_BY_AB_100',1401:'DST_BY_AB_1000',283:'DST_BY_AB_200',188:'DST_BY_AB_100',1743:'DST_BY_AB_1000',
117:'DST_BY_AB_100',146:'DST_BY_AB_100',117:'DST_BY_AB_100',146:'DST_BY_AB_100',0:'DST_BY_BL_50',115:'DST_BY_AB_100',
114:'DST_BY_AB_100',146:'DST_BY_AB_100',146:'DST_BY_AB_100',606:'DST_BY_AB_600',396:'DST_BY_AB_300',2650:'DST_BY_AB_2000',
349:'DST_BY_AB_300',9885:'DST_BY_AB_9000',345:'DST_BY_AB_300',0:'DST_BY_BL_50',146:'DST_BY_AB_100',0:'DST_BY_BL_50',
146:'DST_BY_AB_100',294:'DST_BY_AB_200',631:'DST_BY_AB_600',110:'DST_BY_AB_100',6787:'DST_BY_AB_6000',412:'DST_BY_AB_400',
115:'DST_BY_AB_100',146:'DST_BY_AB_100',145:'DST_BY_AB_100',294:'DST_BY_AB_200',2199:'DST_BY_AB_2000',383476:'DST_BY_AB_300000',
333:'DST_BY_AB_300',146:'DST_BY_AB_100',1432:'DST_BY_AB_1000',5141:'DST_BY_AB_5000',146:'DST_BY_AB_100',4191:'DST_BY_AB_4000',
19012:'DST_BY_AB_10000',146:'DST_BY_AB_100',321:'DST_BY_AB_300',5200:'DST_BY_AB_5000',6924:'DST_BY_AB_6000',146:'DST_BY_AB_100',
110:'DST_BY_AB_100',113:'DST_BY_AB_100',146:'DST_BY_AB_100',3113:'DST_BY_AB_3000',264:'DST_BY_AB_200',2026:'DST_BY_AB_2000',
115:'DST_BY_AB_100',146:'DST_BY_AB_100',146:'DST_BY_AB_100',2393:'DST_BY_AB_2000',308:'DST_BY_AB_300',146:'DST_BY_AB_100',
0:'DST_BY_BL_50',2219:'DST_BY_AB_2000',0:'DST_BY_BL_50',0:'DST_BY_BL_50',146:'DST_BY_AB_100',412:'DST_BY_AB_400',
3313:'DST_BY_AB_3000',1512:'DST_BY_AB_1000',799:'DST_BY_AB_700',1733:'DST_BY_AB_1000',
327:'DST_BY_AB_300',673:'DST_BY_AB_600',1549:'DST_BY_AB_1000',371:'DST_BY_AB_300',22633:'DST_BY_AB_20000',2427:'DST_BY_AB_2000',
379:'DST_BY_AB_300',1707:'DST_BY_AB_1000',603:'DST_BY_AB_600',146:'DST_BY_AB_100',6839:'DST_BY_AB_6000',
285:'DST_BY_AB_200',146:'DST_BY_AB_100',27:'DST_BY_BL_50',391:'DST_BY_AB_300',1289:'DST_BY_AB_1000',1713:'DST_BY_AB_1000',
292:'DST_BY_AB_200',273:'DST_BY_AB_200',19012:'DST_BY_AB_10000',146:'DST_BY_AB_100',354:'DST_BY_AB_300',1053:'DST_BY_AB_1000',
821:'DST_BY_AB_800',6248:'DST_BY_AB_6000',2521:'DST_BY_AB_2000',327:'DST_BY_AB_300',407:'DST_BY_AB_400',193:'DST_BY_AB_100',
603:'DST_BY_AB_600',2427:'DST_BY_AB_2000',146:'DST_BY_AB_100',525:'DST_BY_AB_500',146:'DST_BY_AB_100',9189:'DST_BY_AB_9000',
741:'DST_BY_AB_700',146:'DST_BY_AB_100',146:'DST_BY_AB_100',2427:'DST_BY_AB_2000',146:'DST_BY_AB_100',146:'DST_BY_AB_100',
14274:'DST_BY_AB_10000',2427:'DST_BY_AB_2000',492:'DST_BY_AB_400',667:'DST_BY_AB_600',334:'DST_BY_AB_300',6104:'DST_BY_AB_6000',
146:'DST_BY_AB_100',110:'DST_BY_AB_100',431:'DST_BY_AB_400',1197:'DST_BY_AB_1000',146:'DST_BY_AB_100',1574:'DST_BY_AB_1000',
382:'DST_BY_AB_300',1743:'DST_BY_AB_1000',633:'DST_BY_AB_600',124:'DST_BY_AB_100',115:'DST_BY_AB_100',146:'DST_BY_AB_100',
4:'DST_BY_BL_50',146:'DST_BY_AB_100',32473:'DST_BY_AB_30000',146:'DST_BY_AB_100',6104:'DST_BY_AB_6000',353:'DST_BY_AB_300',
12502:'DST_BY_AB_10000',873:'DST_BY_AB_800',146:'DST_BY_AB_100',4555:'DST_BY_AB_4000',146:'DST_BY_AB_100',329:'DST_BY_AB_300',
283:'DST_BY_AB_200',1812:'DST_BY_AB_1000',406:'DST_BY_AB_400',372:'DST_BY_AB_1000',468:'DST_BY_AB_400',1791:'DST_BY_AB_1000',
699:'DST_BY_AB_600',115:'DST_BY_AB_100',302:'DST_BY_AB_300',146:'DST_BY_AB_100',13166:'DST_BY_AB_10000',603:'DST_BY_AB_600',
1797:'DST_BY_AB_1000',278:'DST_BY_AB_200',289:'DST_BY_AB_200',1745:'DST_BY_AB_1000',675:'DST_BY_AB_600',146:'DST_BY_AB_100',
810:'DST_BY_AB_800',117:'DST_BY_AB_100',117:'DST_BY_AB_100',146:'DST_BY_AB_100',1697:'DST_BY_AB_1000',1850:'DST_BY_AB_1000',
283:'DST_BY_AB_200',897:'DST_BY_AB_800',146:'DST_BY_AB_100',101:'DST_BY_AB_100',452:'DST_BY_AB_400',188:'DST_BY_AB_100',
197:'DST_BY_AB_100',1161:'DST_BY_AB_1000',196:'DST_BY_AB_100',1549:'DST_BY_AB_1000',402:'DST_BY_AB_400',1134:'DST_BY_AB_1000',
2427:'DST_BY_AB_2000',17455:'DST_BY_AB_10000',2348:'DST_BY_AB_2000',
524:'DST_BY_AB_500',1134:'DST_BY_AB_1000',371:'DST_BY_AB_300',1193:'DST_BY_AB_1000',3548:'DST_BY_AB_3000',
13425:'DST_BY_AB_10000',
146:'DST_BY_AB_100',146:'DST_BY_AB_100',821:'DST_BY_AB_800',403:'DST_BY_AB_400',401:'DST_BY_AB_400',4841:'DST_BY_AB_4000',
146:'DST_BY_AB_100',146:'DST_BY_AB_100',327:'DST_BY_AB_300',10022:'DST_BY_AB_10000',146:'DST_BY_AB_100',146:'DST_BY_AB_100',
938:'DST_BY_AB_900',196:'DST_BY_AB_100',194:'DST_BY_AB_100',146:'DST_BY_AB_100',325:'DST_BY_AB_300',3188:'DST_BY_AB_3000',
818:'DST_BY_AB_800',9571:'DST_BY_AB_9000',2096:'DST_BY_AB_2000',331:'DST_BY_AB_300',146:'DST_BY_AB_100',320:'DST_BY_AB_300',
258:'DST_BY_AB_200',0:'DST_BY_BL_50',564:'DST_BY_AB_500',394:'DST_BY_AB_300',1034:'DST_BY_AB_1000',1667:'DST_BY_AB_1000',
146:'DST_BY_AB_100',113:'DST_BY_AB_100',402:'DST_BY_AB_400',107:'DST_BY_AB_100',335:'DST_BY_AB_300',43:'DST_BY_BL_50',
257:'DST_BY_AB_200',685:'DST_BY_AB_600',146:'DST_BY_AB_100',392:'DST_BY_AB_300',22145:'DST_BY_AB_20000',1667:'DST_BY_AB_1000',
146:'DST_BY_AB_100',7969:'DST_BY_AB_7000',146:'DST_BY_AB_100',146:'DST_BY_AB_100',1047:'DST_BY_AB_1000',146:'DST_BY_AB_100',
10572:'DST_BY_AB_10000',334:'DST_BY_AB_300',146:'DST_BY_AB_100',146:'DST_BY_AB_100',473:'DST_BY_AB_400',340:'DST_BY_AB_300',
331:'DST_BY_AB_300',411:'DST_BY_AB_400',115:'DST_BY_AB_100',327:'DST_BY_AB_300',
770:'DST_BY_AB_700',396:'DST_BY_AB_300',16082:'DST_BY_AB_10000',313:'DST_BY_AB_300',146:'DST_BY_AB_100',
0:'DST_BY_BL_50',332:'DST_BY_AB_300',4378:'DST_BY_AB_4000',753:'DST_BY_AB_700',146:'DST_BY_AB_100',115:'DST_BY_AB_100',
146:'DST_BY_AB_100',16147:'DST_BY_AB_10000',146:'DST_BY_AB_100',1047:'DST_BY_AB_1000',329:'DST_BY_AB_300',107:'DST_BY_AB_100',
482:'DST_BY_AB_400',330:'DST_BY_AB_300',0:'DST_BY_BL_50',35576:'DST_BY_AB_30000',146:'DST_BY_AB_100',3973:'DST_BY_AB_3000',
1379:'DST_BY_AB_1000',7873:'DST_BY_AB_7000',903:'DST_BY_AB_900',146:'DST_BY_AB_100',0:'DST_BY_BL_50',146:'DST_BY_AB_100',
1437:'DST_BY_AB_1000',146:'DST_BY_AB_100',146:'DST_BY_AB_100',1850:'DST_BY_AB_1000',188:'DST_BY_AB_100',
675:'DST_BY_AB_600',1402:'DST_BY_AB_1000',874:'DST_BY_AB_800',332:'DST_BY_AB_300',146:'DST_BY_AB_100',18718:'DST_BY_AB_10000',
775:'DST_BY_AB_700',1063:'DST_BY_AB_1000',146:'DST_BY_AB_100',115:'DST_BY_AB_100',7344:'DST_BY_AB_7000',6788:'DST_BY_AB_6000',
2093:'DST_BY_AB_2000',2862:'DST_BY_AB_2000',326:'DST_BY_AB_300',110:'DST_BY_AB_100',1193:'DST_BY_AB_1000',5972:'DST_BY_AB_5000',
0:'DST_BY_BL_50',146:'DST_BY_AB_100',3331:'DST_BY_AB_3000',7439:'DST_BY_AB_7000',486:'DST_BY_AB_400',9392:'DST_BY_AB_9000',
146:'DST_BY_AB_100',110:'DST_BY_AB_100',4:'DST_BY_BL_50',26625:'DST_BY_AB_20000',146:'DST_BY_AB_100',3060:'DST_BY_AB_3000',
342:'DST_BY_AB_300',407:'DST_BY_AB_400',14607:'DST_BY_AB_10000',5064:'DST_BY_AB_5000',146:'DST_BY_AB_100',64498:'DST_BY_AB_60000',
634:'DST_BY_AB_600',4897:'DST_BY_AB_4000',306:'DST_BY_AB_300',332:'DST_BY_AB_300',1047:'DST_BY_AB_1000',5381:'DST_BY_AB_5000',
1212:'DST_BY_AB_1000',12341:'DST_BY_AB_10000',330:'DST_BY_AB_300',1047:'DST_BY_AB_1000',146:'DST_BY_AB_100',
146:'DST_BY_AB_100',
309:'DST_BY_AB_300',
0:'DST_BY_BL_50',146:'DST_BY_AB_100',1587:'DST_BY_AB_1000',146:'DST_BY_AB_100',146:'DST_BY_AB_100',146:'DST_BY_AB_100',
375:'DST_BY_AB_300',146:'DST_BY_AB_100',9929:'DST_BY_AB_9000',146:'DST_BY_AB_100',593:'DST_BY_AB_500',3855:'DST_BY_AB_3000',
2239:'DST_BY_AB_2000',146:'DST_BY_AB_100',146:'DST_BY_AB_100',146:'DST_BY_AB_100',1047:'DST_BY_AB_1000',3115:'DST_BY_AB_3000',
146:'DST_BY_AB_100',347:'DST_BY_AB_300',1573:'DST_BY_AB_1000',3551:'DST_BY_AB_3000',2156:'DST_BY_AB_2000',1984:'DST_BY_AB_1000',
294:'DST_BY_AB_200',336:'DST_BY_AB_300',531:'DST_BY_AB_500',332:'DST_BY_AB_300',4058:'DST_BY_AB_4000',430:'DST_BY_AB_400',
241:'DST_BY_AB_200',146:'DST_BY_AB_100',44:'DST_BY_BL_50',2702:'DST_BY_AB_2000',2199:'DST_BY_AB_2000',4947:'DST_BY_AB_4000',
586:'DST_BY_AB_500',146:'DST_BY_AB_100',468:'DST_BY_AB_400',345:'DST_BY_AB_300',0:'DST_BY_BL_50',1587:'DST_BY_AB_1000',
588:'DST_BY_AB_500',2445:'DST_BY_AB_2000',5893:'DST_BY_AB_5000',2772:'DST_BY_AB_2000',334:'DST_BY_AB_300',2443:'DST_BY_AB_2000',
753:'DST_BY_AB_700',1496:'DST_BY_AB_1000',1047:'DST_BY_AB_1000',3222:'DST_BY_AB_3000',1359:'DST_BY_AB_1000',
3463:'DST_BY_AB_3000',
943:'DST_BY_AB_900',146:'DST_BY_AB_100',10624:'DST_BY_AB_10000',3222:'DST_BY_AB_3000',146:'DST_BY_AB_100',2702:'DST_BY_AB_2000',
631:'DST_BY_AB_600',753:'DST_BY_AB_700',16696:'DST_BY_AB_10000',870:'DST_BY_AB_800',146:'DST_BY_AB_100',35014:'DST_BY_AB_30000',
1093:'DST_BY_AB_1000',1372:'DST_BY_AB_1000',146:'DST_BY_AB_100',146:'DST_BY_AB_100',146:'DST_BY_AB_100',308:'DST_BY_AB_300',
520:'DST_BY_AB_500',17588:'DST_BY_AB_10000',709:'DST_BY_AB_700',1030:'DST_BY_AB_1000',870:'DST_BY_AB_800',388:'DST_BY_AB_300',
1055:'DST_BY_AB_1000',257:'DST_BY_AB_200',146:'DST_BY_AB_100',755:'DST_BY_AB_700',185:'DST_BY_AB_100',753:'DST_BY_AB_700',
307:'DST_BY_AB_300',259:'DST_BY_AB_200',190:'DST_BY_AB_100',2427:'DST_BY_AB_2000',2445:'DST_BY_AB_2000',6924:'DST_BY_AB_6000',
146:'DST_BY_AB_100',664:'DST_BY_AB_600',1266:'DST_BY_AB_1000',146:'DST_BY_AB_100',145:'DST_BY_AB_100',3222:'DST_BY_AB_3000',
4471:'DST_BY_AB_4000',146:'DST_BY_AB_100',1212:'DST_BY_AB_1000',9207:'DST_BY_AB_9000',207796:'DST_BY_AB_200000',
3313:'DST_BY_AB_3000',
 146:'DST_BY_AB_100',2698:'DST_BY_AB_2000',3376:'DST_BY_AB_3000',42:'DST_BY_BL_50',42:'DST_BY_BL_50',42:'DST_BY_BL_50',
 42:'DST_BY_BL_50',42:'DST_BY_BL_50',1965:'DST_BY_AB_1000',770:'DST_BY_AB_700',321:'DST_BY_AB_300',9207:'DST_BY_AB_9000',
1512:'DST_BY_AB_1000',3410:'DST_BY_AB_3000',16082:'DST_BY_AB_10000',146:'DST_BY_AB_100',8712:'DST_BY_AB_8000',
1565:'DST_BY_AB_1000',
42:'DST_BY_BL_50',42:'DST_BY_BL_50',42:'DST_BY_BL_50',42:'DST_BY_BL_50',0:'DST_BY_BL_50',34:'DST_BY_BL_50',
42:'DST_BY_BL_50',45:'DST_BY_BL_50',42:'DST_BY_BL_50',42:'DST_BY_BL_50',42:'DST_BY_BL_50',39:'DST_BY_BL_50',
 42:'DST_BY_BL_50',1565:'DST_BY_AB_1000',1850:'DST_BY_AB_1000',42:'DST_BY_BL_50',673:'DST_BY_AB_600',1743:'DST_BY_AB_1000',
 278:'DST_BY_AB_200',34:'DST_BY_BL_50',42:'DST_BY_BL_50',60530:'DST_BY_AB_60000',42:'DST_BY_BL_50',1047:'DST_BY_AB_1000',
 625:'DST_BY_AB_600',339:'DST_BY_AB_300',13141:'DST_BY_AB_10000',6281:'DST_BY_AB_6000',193:'DST_BY_AB_100',1011:'DST_BY_AB_1000',
 100:'DST_BY_AB_100',146:'DST_BY_AB_100',25519:'DST_BY_AB_20000',1797:'DST_BY_AB_1000',34:'DST_BY_BL_50',9699:'DST_BY_AB_9000',
 11200:'DST_BY_AB_10000',300:'DST_BY_AB_300',6324:'DST_BY_AB_6000',34:'DST_BY_BL_50',2863:'DST_BY_AB_2000',382:'DST_BY_AB_300',
634:'DST_BY_AB_600',1098:'DST_BY_AB_1000',146:'DST_BY_AB_100',1398:'DST_BY_AB_1000',1564:'DST_BY_AB_1000',0:'DST_BY_BL_50',
772:'DST_BY_AB_700',168:'DST_BY_AB_100',146:'DST_BY_AB_100',520:'DST_BY_AB_500',441:'DST_BY_AB_400',1809:'DST_BY_AB_1000',
283:'DST_BY_AB_200',146:'DST_BY_AB_100',146:'DST_BY_AB_100',2772:'DST_BY_AB_2000',267:'DST_BY_AB_200',146:'DST_BY_AB_100',
146:'DST_BY_AB_100',863:'DST_BY_AB_800',306:'DST_BY_AB_300',675:'DST_BY_AB_600',146:'DST_BY_AB_100',146:'DST_BY_AB_100',
1850:'DST_BY_AB_1000',304:'DST_BY_AB_300',188:'DST_BY_AB_100',449:'DST_BY_AB_400',3713:'DST_BY_AB_3000',1471:'DST_BY_AB_1000',
445:'DST_BY_AB_400',
168:'DST_BY_AB_100',3913:'DST_BY_AB_3000',304:'DST_BY_AB_300',1850:'DST_BY_AB_1000',291:'DST_BY_AB_200',675:'DST_BY_AB_600',
197:'DST_BY_AB_100',938:'DST_BY_AB_900',1429:'DST_BY_AB_1000',291:'DST_BY_AB_200',1773:'DST_BY_AB_1000',6989:'DST_BY_AB_6000',
 6291:'DST_BY_AB_6000',169:'DST_BY_AB_100',588:'DST_BY_AB_500',291:'DST_BY_AB_200',309:'DST_BY_AB_300',146:'DST_BY_AB_100',
4904:'DST_BY_AB_4000',291:'DST_BY_AB_200',196:'DST_BY_AB_100',2858:'DST_BY_AB_2000',8557:'DST_BY_AB_8000',402:'DST_BY_AB_400',
2698:'DST_BY_AB_2000',30327:'DST_BY_AB_30000',25519:'DST_BY_AB_20000',2034:'DST_BY_AB_2000',0:'DST_BY_BL_50',
146:'DST_BY_AB_100',
11444:'DST_BY_AB_10000',146:'DST_BY_AB_100',408:'DST_BY_AB_400',44:'DST_BY_BL_50',5247:'DST_BY_AB_5000',1151:'DST_BY_AB_1000',
44:'DST_BY_BL_50',331:'DST_BY_AB_300',146:'DST_BY_AB_100',146:'DST_BY_AB_100',146:'DST_BY_AB_100',459:'DST_BY_AB_400',
146:'DST_BY_AB_100',601:'DST_BY_AB_600',146:'DST_BY_AB_100',46:'DST_BY_BL_50',1930:'DST_BY_AB_1000',1556:'DST_BY_AB_1000',
49759:'DST_BY_AB_40000',6924:'DST_BY_AB_6000',19075:'DST_BY_AB_10000',3200:'DST_BY_AB_3000',0:'DST_BY_BL_50',
146:'DST_BY_AB_100',
326:'DST_BY_AB_300',2153:'DST_BY_AB_2000',3287:'DST_BY_AB_3000',1567:'DST_BY_AB_1000',1009:'DST_BY_AB_1000',331:'DST_BY_AB_300',
146:'DST_BY_AB_100',146:'DST_BY_AB_100',1302:'DST_BY_AB_1000',799:'DST_BY_AB_700',333:'DST_BY_AB_300',115:'DST_BY_AB_100',
42:'DST_BY_BL_50',247:'DST_BY_AB_200',3200:'DST_BY_AB_3000',526:'DST_BY_AB_500',402:'DST_BY_AB_400',5338:'DST_BY_AB_5000',
114:'DST_BY_AB_100',114:'DST_BY_AB_100',42:'DST_BY_BL_50',114:'DST_BY_AB_100',114:'DST_BY_AB_100',4823:'DST_BY_AB_4000',
3582:'DST_BY_AB_3000',4033:'DST_BY_AB_4000',1326:'DST_BY_AB_1000',755:'DST_BY_AB_700',181:'DST_BY_AB_100',1284:'DST_BY_AB_1000',
3200:'DST_BY_AB_3000',526:'DST_BY_AB_500',13057:'DST_BY_AB_10000',146:'DST_BY_AB_100',257:'DST_BY_AB_200',6045:'DST_BY_AB_6000',
674:'DST_BY_AB_600',1150:'DST_BY_AB_1000',146:'DST_BY_AB_100',283:'DST_BY_AB_200',436:'DST_BY_AB_400',42:'DST_BY_BL_50',
146:'DST_BY_AB_100',146:'DST_BY_AB_100',113:'DST_BY_AB_100',13057:'DST_BY_AB_10000',146:'DST_BY_AB_100',329:'DST_BY_AB_300',
5681:'DST_BY_AB_5000',1466:'DST_BY_AB_1000',330:'DST_BY_AB_300',2975:'DST_BY_AB_2000',5190:'DST_BY_AB_5000',1383:'DST_BY_AB_1000',
42:'DST_BY_BL_50',855:'DST_BY_AB_800',146:'DST_BY_AB_100',146:'DST_BY_AB_100',0:'DST_BY_BL_50',324:'DST_BY_AB_300',
2507:'DST_BY_AB_2000',1047:'DST_BY_AB_1000',366:'DST_BY_AB_300',193:'DST_BY_AB_100',1227:'DST_BY_AB_1000',146:'DST_BY_AB_100',
15820:'DST_BY_AB_10000',38:'DST_BY_BL_50',483:'DST_BY_AB_400',146:'DST_BY_AB_100',25080:'DST_BY_AB_20000',638:'DST_BY_AB_600',
2053:'DST_BY_AB_2000',1734:'DST_BY_AB_1000',272:'DST_BY_AB_200',339:'DST_BY_AB_300',146:'DST_BY_AB_100',2698:'DST_BY_AB_2000',
146:'DST_BY_AB_100',146:'DST_BY_AB_100',1047:'DST_BY_AB_1000',820:'DST_BY_AB_800',990:'DST_BY_AB_900',866:'DST_BY_AB_800',
12304:'DST_BY_AB_10000',45263:'DST_BY_AB_40000',483:'DST_BY_AB_400',37:'DST_BY_BL_50',3443:'DST_BY_AB_3000',146:'DST_BY_AB_100',
115:'DST_BY_AB_100',502:'DST_BY_AB_500',328:'DST_BY_AB_300',5683:'DST_BY_AB_5000',146:'DST_BY_AB_100',392:'DST_BY_AB_300',
3433:'DST_BY_AB_3000',160:'DST_BY_AB_100',55605:'DST_BY_AB_50000',146:'DST_BY_AB_100',392:'DST_BY_AB_300',146:'DST_BY_AB_100',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50', 0:'DST_BY_BL_50',0:'DST_BY_BL_50',0:'DST_BY_BL_50',
0:'DST_BY_BL_50'})

In [44]:
df=df.dropna()

In [45]:
df['DSTBY'].unique()

array(['DST_BY_AB_100', 'DST_BY_BL_50', 'DST_BY_AB_200', 'DST_BY_AB_300',
       'DST_BY_AB_10000', 'DST_BY_AB_3000', 'DST_BY_AB_700',
       'DST_BY_AB_9000', 'DST_BY_AB_8000', 'DST_BY_AB_600',
       'DST_BY_AB_2000', 'DST_BY_AB_7000', 'DST_BY_AB_1000',
       'DST_BY_AB_4000', 'DST_BY_AB_5000', 'DST_BY_AB_500',
       'DST_BY_AB_400', 'DST_BY_AB_900', 'DST_BY_AB_6000',
       'DST_BY_AB_300000', 'DST_BY_AB_20000', 'DST_BY_AB_800',
       'DST_BY_AB_30000', 'DST_BY_AB_60000', 'DST_BY_AB_200000',
       'DST_BY_AB_40000', 'DST_BY_AB_50000'], dtype=object)

In [46]:
df['DST_BY_AB_100'] = df.DSTBY.map({'DST_BY_AB_100':1, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_BL_50'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':1, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_200'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':1, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_300'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':1,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_10000'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':1, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_3000'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':1, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})

In [47]:
df['DST_BY_AB_700'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':1,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_9000'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':1, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_8000'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':1, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_600'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':1,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_2000'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':1, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_7000'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':1, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})

In [48]:
df['DST_BY_AB_1000'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':1,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_4000'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':1, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_5000'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':1, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_500'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':1,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_400'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':1, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_900'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':1, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})

In [49]:
df['DST_BY_AB_6000'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':1,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_300000'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':1, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_20000'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':1, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_800'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':1,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_30000'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':1, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_60000'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':1, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})

In [50]:
df['DST_BY_AB_200000'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':1,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':0})
df['DST_BY_AB_40000'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':1, 'DST_BY_AB_50000':0})
df['DST_BY_AB_50000'] = df.DSTBY.map({'DST_BY_AB_100':0, 'DST_BY_BL_50':0, 'DST_BY_AB_200':0, 'DST_BY_AB_300':0,
'DST_BY_AB_10000':0, 'DST_BY_AB_3000':0, 'DST_BY_AB_700':0,'DST_BY_AB_9000':0, 'DST_BY_AB_8000':0, 'DST_BY_AB_600':0,
'DST_BY_AB_2000':0, 'DST_BY_AB_7000':0, 'DST_BY_AB_1000':0,'DST_BY_AB_4000':0, 'DST_BY_AB_5000':0, 'DST_BY_AB_500':0,
'DST_BY_AB_400':0, 'DST_BY_AB_900':0, 'DST_BY_AB_6000':0,'DST_BY_AB_300000':0, 'DST_BY_AB_20000':0, 'DST_BY_AB_800':0,
'DST_BY_AB_30000':0, 'DST_BY_AB_60000':0, 'DST_BY_AB_200000':0,'DST_BY_AB_40000':0, 'DST_BY_AB_50000':1})

In [51]:
del df['dst_bytes']
del df['DSTBY']
del df['SRCBY']
del df['Wrong_fragment']
del df['serror_rate']
del df['rerror_rate']

In [52]:
df.head()

,class,attack,Attack_Type,UDP,TCP,ICMP,private,domain_u,http,smtp,...,DST_BY_AB_900,DST_BY_AB_6000,DST_BY_AB_300000,DST_BY_AB_20000,DST_BY_AB_800,DST_BY_AB_30000,DST_BY_AB_60000,DST_BY_AB_200000,DST_BY_AB_40000,DST_BY_AB_50000
0,normal.,0,No_Attack_Occurs,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,normal.,0,No_Attack_Occurs,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,normal.,0,No_Attack_Occurs,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,snmpgetattack.,1,SNMPget_Attack,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,snmpgetattack.,1,SNMPget_Attack,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [53]:
df.columns

Index(['class', 'attack', 'Attack_Type', 'UDP', 'TCP', 'ICMP', 'private',
       'domain_u', 'http', 'smtp',
       ...
       'DST_BY_AB_900', 'DST_BY_AB_6000', 'DST_BY_AB_300000',
       'DST_BY_AB_20000', 'DST_BY_AB_800', 'DST_BY_AB_30000',
       'DST_BY_AB_60000', 'DST_BY_AB_200000', 'DST_BY_AB_40000',
       'DST_BY_AB_50000'],
      dtype='object', length=139)

In [54]:
l1=['SRC_BY_BL_50', 'SRC_BY_AB_100', 'SRC_BY_AB_200', 'SRC_BY_AB_3000',
       'SRC_BY_AB_700', 'SRC_BY_AB_30000', 'SRC_BY_AB_8000', 'SRC_BY_AB_500',
       'SRC_BY_AB_300', 'SRC_BY_AB_1000', 'SRC_BY_AB_600', 'SRC_BY_AB_900',
       'SRC_BY_AB_800', 'SRC_BY_AB_10000', 'SRC_BY_AB_2000',
       'SRC_BY_AB_200000', 'SRC_BY_AB_400', 'SRC_BY_AB_50000',
       'SRC_BY_AB_5000', 'SRC_BY_AB_4000', 'SRC_BY_AB_30000000',
       'SRC_BY_AB_7000', 'SRC_BY_AB_1000000', 'SRC_BY_AB_6000',
       'SRC_BY_AB_60000', 'SRC_BY_AB_100000', 'SRC_BY_AB_500000',
       'SRC_BY_AB_40000', 'SRC_BY_AB_9000', 'SRC_BY_AB_20000',
       'SRC_BY_AB_80000', 'SRC_BY_AB_90000', 'SRC_BY_AB_70000']

In [55]:
l2=['DST_BY_AB_100', 'DST_BY_BL_50', 'DST_BY_AB_200', 'DST_BY_AB_300',
       'DST_BY_AB_10000', 'DST_BY_AB_3000', 'DST_BY_AB_700', 'DST_BY_AB_9000',
       'DST_BY_AB_8000', 'DST_BY_AB_600', 'DST_BY_AB_2000', 'DST_BY_AB_7000',
       'DST_BY_AB_1000', 'DST_BY_AB_4000', 'DST_BY_AB_5000', 'DST_BY_AB_500',
       'DST_BY_AB_400', 'DST_BY_AB_900', 'DST_BY_AB_6000', 'DST_BY_AB_300000',
       'DST_BY_AB_20000', 'DST_BY_AB_800', 'DST_BY_AB_30000',
       'DST_BY_AB_60000', 'DST_BY_AB_200000', 'DST_BY_AB_40000',
       'DST_BY_AB_50000']

In [56]:
l3=['UDP', 'TCP','ICMP']

In [57]:
l4=['SF', 'RSTR', 'S1', 'REJ', 'S3', 'RSTO', 'S0', 'S2']

In [58]:
l5=['private', 'domain_u', 'http', 'smtp', 'ftp_data', 'ftp','eco_i', 'other', 'auth', 'ecr_i', 'IRC', 'X11', 'finger', 'time',
       'domain', 'telnet', 'pop_3', 'ldap', 'login', 'name', 'ntp_u',
       'http_443', 'sunrpc', 'printer', 'systat', 'tim_i','netstat', 'remote_job',
       'link', 'urp_i', 'sql_net', 'bgp', 'pop_2', 'tftp_u', 'uucp',
       'imap4', 'pm_dump', 'nnsp', 'courier', 'daytime', 'iso_tsap',
       'echo', 'discard', 'ssh', 'whois', 'mtp', 'gopher', 'rje', 'ctf',
       'supdup', 'hostnames', 'csnet_ns', 'uucp_path', 'nntp',
       'netbios_ns', 'netbios_dgm', 'netbios_ssn', 'vmnet', 'Z39_50',
       'exec', 'shell', 'efs', 'klogin', 'kshell', 'icmp']

In [59]:
l6=['SRC_BY_BL_50', 'SRC_BY_AB_100', 'SRC_BY_AB_200', 'SRC_BY_AB_3000',
       'SRC_BY_AB_700', 'SRC_BY_AB_30000', 'SRC_BY_AB_8000', 'SRC_BY_AB_500',
       'SRC_BY_AB_300', 'SRC_BY_AB_1000', 'SRC_BY_AB_600', 'SRC_BY_AB_900',
       'SRC_BY_AB_800', 'SRC_BY_AB_10000', 'SRC_BY_AB_2000',
       'SRC_BY_AB_200000', 'SRC_BY_AB_400', 'SRC_BY_AB_50000',
       'SRC_BY_AB_5000', 'SRC_BY_AB_4000', 'SRC_BY_AB_30000000',
       'SRC_BY_AB_7000', 'SRC_BY_AB_1000000', 'SRC_BY_AB_6000',
       'SRC_BY_AB_60000', 'SRC_BY_AB_100000', 'SRC_BY_AB_500000',
       'SRC_BY_AB_40000', 'SRC_BY_AB_9000', 'SRC_BY_AB_20000',
       'SRC_BY_AB_80000', 'SRC_BY_AB_90000', 'SRC_BY_AB_70000','DST_BY_AB_100', 'DST_BY_BL_50', 'DST_BY_AB_200', 'DST_BY_AB_300',
       'DST_BY_AB_10000', 'DST_BY_AB_3000', 'DST_BY_AB_700', 'DST_BY_AB_9000',
       'DST_BY_AB_8000', 'DST_BY_AB_600', 'DST_BY_AB_2000', 'DST_BY_AB_7000',
       'DST_BY_AB_1000', 'DST_BY_AB_4000', 'DST_BY_AB_5000', 'DST_BY_AB_500',
       'DST_BY_AB_400', 'DST_BY_AB_900', 'DST_BY_AB_6000', 'DST_BY_AB_300000',
       'DST_BY_AB_20000', 'DST_BY_AB_800', 'DST_BY_AB_30000',
       'DST_BY_AB_60000', 'DST_BY_AB_200000', 'DST_BY_AB_40000',
       'DST_BY_AB_50000','UDP', 'TCP','ICMP','SF', 'RSTR', 'S1', 'REJ', 'S3', 'RSTO', 'S0', 'S2','private', 'domain_u', 'http', 'smtp', 'ftp_data', 'ftp','eco_i', 'other', 'auth', 'ecr_i', 'IRC', 'X11', 'finger', 'time',
       'domain', 'telnet', 'pop_3', 'ldap', 'login', 'name', 'ntp_u',
       'http_443', 'sunrpc', 'printer', 'systat', 'tim_i' ,'netstat', 'remote_job',
       'link', 'urp_i', 'sql_net', 'bgp', 'pop_2', 'tftp_u', 'uucp',
       'imap4', 'pm_dump', 'nnsp', 'courier', 'daytime', 'iso_tsap',
       'echo', 'discard', 'ssh', 'whois', 'mtp', 'gopher', 'rje', 'ctf',
       'supdup', 'hostnames', 'csnet_ns', 'uucp_path', 'nntp',
       'netbios_ns', 'netbios_dgm', 'netbios_ssn', 'vmnet', 'Z39_50',
       'exec', 'shell', 'efs', 'klogin', 'kshell', 'icmp']

In [60]:
df['Attack_Type'].unique()

array(['No_Attack_Occurs', 'SNMPget_Attack', 'Named_Attack',
       'Xlock_Attack', 'Smurf_Attack', 'IPsweep_Attack',
       'Multihop_Attack', 'Sendmail_Attack', 'Saint_Attack',
       'Portsweep_Attack', 'Pod_Attack', 'Apache2_Attack', 'PHF_Attack',
       'UDPstorm_Attack', 'Warezmaster_Attack', 'Satan_Attack',
       'Mscan_Attack', 'Processtable_Attack', 'Rootkit_Attack',
       'Neptune_Attack', 'PS_Attack', 'HTTPtunnel_Attack',
       'Guess_passwd_Attack', 'FTP_Write_Attack', 'Land_Attack',
       'SNMPguess_Attack'], dtype=object)

In [61]:
decision = ['No_Attack_Occurs', 'SNMPget_Attack', 'Named_Attack',
       'Xlock_Attack', 'Smurf_Attack', 'IPsweep_Attack',
       'Multihop_Attack', 'Sendmail_Attack', 'Saint_Attack',
       'Portsweep_Attack', 'Pod_Attack', 'Apache2_Attack', 'PHF_Attack',
       'UDPstorm_Attack', 'Warezmaster_Attack', 'Satan_Attack',
       'Mscan_Attack', 'Processtable_Attack', 'Rootkit_Attack',
       'Neptune_Attack', 'PS_Attack', 'HTTPtunnel_Attack',
       'Guess_passwd_Attack', 'FTP_Write_Attack', 'Land_Attack',
       'SNMPguess_Attack']

In [62]:
l7=[]
for x in range(0,len(l6)):
    l7.append(0)

In [63]:
df.replace({'Attack_Type':{'No_Attack_Occurs':0, 'SNMPget_Attack':1, 'Named_Attack':2,
       'Xlock_Attack':3, 'Smurf_Attack':4, 'IPsweep_Attack':5,
       'Multihop_Attack':6, 'Sendmail_Attack':7, 'Saint_Attack':8,
       'Portsweep_Attack':9, 'Pod_Attack':10, 'Apache2_Attack':11, 'PHF_Attack':12,
       'UDPstorm_Attack':13, 'Warezmaster_Attack':14, 'Satan_Attack':15,
       'Mscan_Attack':16, 'Processtable_Attack':17, 'Rootkit_Attack':18,
       'Neptune_Attack':19, 'PS_Attack':20, 'HTTPtunnel_Attack':21,
       'Guess_passwd_Attack':22, 'FTP_Write_Attack':23, 'Land_Attack':24,
       'SNMPguess_Attack':25}},inplace=True)

In [64]:
import numpy as np

In [65]:
Xd= df[l6]


yd = df[["Attack_Type"]]
np.ravel(yd)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [66]:
import numpy as np
X_testd= df[l6]
y_testd = df[["Attack_Type"]]
np.ravel(y_testd)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [67]:
def RandomForestClassifier():
    from sklearn.ensemble import RandomForestClassifier

    gnb = RandomForestClassifier()
    gnb=gnb.fit(Xd,np.ravel(yd))

    # calculating accuracy-------------------------------------------------------------------
    from sklearn.metrics import accuracy_score
    y_predd=gnb.predict(X_testd)
    print(accuracy_score(y_testd, y_predd))
    
    print(accuracy_score(y_testd, y_predd,normalize=False))
   
    # -----------------------------------------------------
    terms = [src.get(),dst.get(),prt.get(),fl.get(),ser.get()]

    
    for k in range(0,len(l6)):
        for z in terms:
            if(z==l6[k]):
                l7[k]=1

    inputtest = [l7]
    predict = gnb.predict(inputtest)
    predicted=predict[0]

    h='no'
    for a in range(0,len(decision)):
        if(predicted == a):
            h='yes'
            break

    if (h=='yes'):
        t1.delete("1.0", END)
        t1.insert(END, decision[a])
    else:
        t1.delete("1.0", END)
        t1.insert(END, "Not Found")

In [68]:

root1 = Tk()
root1.title("Prediction of Network Attacks")
#root1.configure(background='black')

''

In [69]:
root = Canvas(root1,width=1620,height=1800)
root.pack()
photo = PhotoImage(file ='im3.png')
root.create_image(0,0,image=photo,anchor=NW)

TclError: couldn't open "im3.png": no such file or directory

In [ ]:
src = StringVar()
src.set(None)

dst = StringVar()
dst.set(None)

prt = StringVar()
prt.set(None)

fl = StringVar()
fl.set(None)

ser = StringVar()
ser.set(None)

In [ ]:
# Heading
w2 = Label(root, justify=LEFT, text="Network attack prediction using Machine Learning", fg="red", bg="white")
w2.config(font=("Elephant", 20))
w2.grid(row=1, column=0, columnspan=2, padx=100)
w2 = Label(root, justify=LEFT, text="DoS, R2L, U2R and Probe Types ", fg="blue")
w2.config(font=("Aharoni", 15))
w2.grid(row=2, column=0, columnspan=2, padx=100)

In [ ]:
# labels
srcLb = Label(root, text="Source File Size(in BY):")
srcLb.grid(row=6, column=0, pady=15, sticky=W)

dstLb = Label(root, text="Destination File Size(in BY):")
dstLb.grid(row=7, column=0, pady=15, sticky=W)

prtLb = Label(root, text="Protocol Type:")
prtLb.grid(row=8, column=0, pady=15, sticky=W)

flLb = Label(root, text="Flag Type:")
flLb.grid(row=9, column=0, pady=15, sticky=W)

serLb = Label(root, text="Select services:")
serLb.grid(row=10, column=0, pady=15, sticky=W)

In [ ]:


lrdLb = Label(root, text="Attack_Type", fg="white", bg="red")
lrdLb.grid(row=13, column=0, pady=10, sticky=W)

In [ ]:
# entries
OPTIONSsrc = sorted(l1)
OPTIONSdst = sorted(l2)
OPTIONSprt = sorted(l3)
OPTIONSfl = sorted(l4)
OPTIONSser = sorted(l5)

In [ ]:
srcEn = OptionMenu(root, src,*OPTIONSsrc)
srcEn.grid(row=6, column=1)

dstEn = OptionMenu(root, dst,*OPTIONSdst)
dstEn.grid(row=7, column=1)

prtEn = OptionMenu(root, prt,*OPTIONSprt)
prtEn.grid(row=8, column=1)

flEn = OptionMenu(root, fl,*OPTIONSfl)
flEn.grid(row=9, column=1)

serEn = OptionMenu(root, ser,*OPTIONSser)
serEn.grid(row=10, column=1)

In [ ]:
def clear_display_result():
	t1.delete('1.0',END)

In [ ]:


lrd = Button(root, text="Check Result", command=RandomForestClassifier,bg="cyan",fg="green")
lrd.grid(row=13, column=3,padx=10)

button3=Button(root,text="Reset", command=clear_display_result,width=12,bg="red",fg="white")
button3.grid(row=6,column=3,padx=10,pady=10)

In [ ]:

t1 = Text(root, height=1, width=40,bg="orange",fg="black")
t1.grid(row=13, column=1 , padx=10)




root1.mainloop()